# -*- coding: utf-8 -*-
"""
This module provides the ability to dynamically discover instances & services via our AWS account.

:copyright: (c) 2015 by Urban Compass, Inc.
"""


# AWS resource key names

# An instance user operates all of our managed processes on that particular instance.
INSTANCE_USER_KEY = 'InstanceUser'

# An environment represents one or more instances that collectively form a single "operational unit"
# running our code.
INSTANCE_ENVIRONMENT_KEY = 'InstanceEnvironment'

# An instance's "purpose" is conceptually similar to a fabric "role" but is independent of the
# instance's environment (i.e. staging, production, development).
INSTANCE_PURPOSE_KEY = 'InstancePurpose'


# An instance's owner is the person/team responsible for maintenance of the instance. This is used
# to track down who's responsible for a machine.
INSTANCE_OWNER_KEY = 'InstanceOwner'


# User-related default values
#   N.B.: These exist for convenience & informational purposes only. The instance discovery
#   framework itself is ignorant of static environment / role / user definitions by design.

INSTANCE_USER_DEFAULT = 'urbancompass'
INSTANCE_ADMIN_USER_DEFAULT = 'ubuntu'

KNOWN_INSTANCE_USERS = (
  INSTANCE_USER_DEFAULT,
)


# Environment-related default values
#   N.B.: These exist for convenience & informational purposes only. The instance discovery
#   framework itself is ignorant of static environment / role / user definitions by design.

INSTANCE_ENVIRONMENT_DEVELOPMENT = 'development'
INSTANCE_ENVIRONMENT_STAGING = 'staging'
INSTANCE_ENVIRONMENT_PRODUCTION = 'production'
INSTANCE_ENVIRONMENT_LOAD_TESTING = 'load_test'

DEVELOPMENT_PEM_FILE = 'development.pem'
PRODUCTION_PEM_FILE = 'production.pem'

KNOWN_INSTANCE_ENVIRONMENTS = frozenset((
  INSTANCE_ENVIRONMENT_DEVELOPMENT,
  INSTANCE_ENVIRONMENT_PRODUCTION,
  INSTANCE_ENVIRONMENT_STAGING,
))

INSTANCE_ENVIRONMENT_SSH_KEY_MAP = {
  INSTANCE_ENVIRONMENT_DEVELOPMENT: DEVELOPMENT_PEM_FILE,
  INSTANCE_ENVIRONMENT_STAGING: DEVELOPMENT_PEM_FILE,
  INSTANCE_ENVIRONMENT_PRODUCTION: PRODUCTION_PEM_FILE,
  INSTANCE_ENVIRONMENT_LOAD_TESTING: DEVELOPMENT_PEM_FILE
}

# Purpose-related default values
#   N.B.: These exist for convenience & informational purposes only. The instance discovery
#   framework itself is ignorant of static environment / role / user definitions by design.

INSTANCE_PURPOSE_ACTIVITY_FEED = 'activity-feed'
INSTANCE_PURPOSE_ACTIVITY_JOBS = 'activity-jobs'
INSTANCE_PURPOSE_ADDRESS_LOOKUP_SERVICE = 'address-lookup-service'
INSTANCE_PURPOSE_AIRFLOW_SCHEDULER = 'airflow-scheduler'
INSTANCE_PURPOSE_AIRFLOW_WORKER = 'airflow-worker'
INSTANCE_PURPOSE_AIRFLOW_WORKER2 = 'airflow-worker2'
INSTANCE_PURPOSE_AIRFLOW_WORKER3 = 'airflow-worker3'
INSTANCE_PURPOSE_ASYNC_IMAGE_PROCESSOR = 'async-image-processor'
INSTANCE_PURPOSE_BASTION = 'bastion'
INSTANCE_PURPOSE_BUILDINGS = 'buildings'
INSTANCE_PURPOSE_BUILDING_EDITORS = 'building-editors'
INSTANCE_PURPOSE_CI = 'continuous-integration'
INSTANCE_PURPOSE_COMMS_CONTACTS_JOBS = 'comms-contacts-jobs'
INSTANCE_PURPOSE_CONTACT_EMAIL = 'contact-email'
INSTANCE_PURPOSE_CONTACTS = 'contacts'
INSTANCE_PURPOSE_COMPASS_QIC = 'compass-qic'
INSTANCE_PURPOSE_CREATIVE_STUDIO = 'creative-studio'
INSTANCE_PURPOSE_DATA_APIS = 'data-apis'
INSTANCE_PURPOSE_DATA_DB = 'data-mongo'
INSTANCE_PURPOSE_DATA_INTEGRATION_TEST = 'data-integration-test'
INSTANCE_PURPOSE_DATA_MONGO_BACKUP = 'data-mongo-backup'
INSTANCE_PURPOSE_DB = 'mongo'
INSTANCE_PURPOSE_DEALS = 'deals'
INSTANCE_PURPOSE_DEALS_JOBS = 'deals-jobs'
INSTANCE_PURPOSE_DEALS_MIGRATORS_SINGLETON = 'deals-migrators-singleton'
INSTANCE_PURPOSE_DEMO = 'demo'
INSTANCE_PURPOSE_DEMO_POOL = 'demo-pool'
INSTANCE_PURPOSE_DEPLOYER = 'deploy'
INSTANCE_PURPOSE_DEVOPS = 'devops'
INSTANCE_PURPOSE_DI_AIRFLOW_BASTION = 'di-airflow-bastion'
INSTANCE_PURPOSE_DOCUMENTS = 'documents'
INSTANCE_PURPOSE_EDITABLE_ACTIVITY = 'editable-activity'
INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER = 'elasticsearch-indexer'
INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER2 = 'elasticsearch-indexer2'
INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER3 = 'elasticsearch-indexer3'
INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER2_LOAD_TEST = 'elasticsearch-indexer2-load-test'
INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER_LOAD_TEST = 'elasticsearch-indexer-load-test'
INSTANCE_PURPOSE_ELASTIC_SEARCH_SEARCHER = 'elasticsearch-searcher'
INSTANCE_PURPOSE_ELASTIC_SEARCH_SEARCHER2 = 'elasticsearch-searcher2'
INSTANCE_PURPOSE_EMAIL_CAMPAIGN = 'email-campaign'
INSTANCE_PURPOSE_EMR_JOBS = 'emr-jobs'
INSTANCE_PURPOSE_EVENTS_APIS = 'events-apis'
INSTANCE_PURPOSE_FIVETRAN_BASTION = 'fivetran-bastion'
INSTANCE_PURPOSE_FF_TUNNELS = 'tunnels'
INSTANCE_PURPOSE_FRONTEND = 'frontend'
INSTANCE_PURPOSE_FRONTEND_CONFIG = 'frontend-config'
INSTANCE_PURPOSE_FRONTEND_PROXY = 'frontend-proxy'
INSTANCE_PURPOSE_FRONTEND_TIER1 = 'frontend-tier1'
INSTANCE_PURPOSE_FTP_TO_S3_MIRROR = 'ftp-to-s3-mirror'
INSTANCE_PURPOSE_GENERIC_JOBS = 'jobs'
INSTANCE_PURPOSE_GEOCODING = 'geocoding'
INSTANCE_PURPOSE_GEOCODING_SERVICE = 'geocoding-service'
INSTANCE_PURPOSE_GI_APPS = 'gi-apps'
INSTANCE_PURPOSE_GIS_SERVICE = 'gis-service'
INSTANCE_PURPOSE_GIS_SERVICE_TEST = 'gis-service-test'
INSTANCE_PURPOSE_GERRIT = 'gerrit'
INSTANCE_PURPOSE_GIS_IMPORTER = 'gis-importer'
INSTANCE_PURPOSE_HELPER_TOOLS = 'helper-tools'
INSTANCE_PURPOSE_IAM_SSH = 'iam-ssh'
INSTANCE_PURPOSE_IDENTITY = 'identity'
INSTANCE_PURPOSE_IMAGE_PROCESSOR = 'image-processor'
INSTANCE_PURPOSE_IMAGE_RESPONSE_PROCESSOR = 'image-response-processor'
INSTANCE_PURPOSE_INDEXER = 'indexer'
INSTANCE_PURPOSE_INDEXER2 = 'indexer2'
INSTANCE_PURPOSE_INDEXER3 = 'indexer3'
INSTANCE_PURPOSE_INDEXER3_LOAD_TEST = 'indexer3-load-test'
INSTANCE_PURPOSE_INDEXER4 = 'indexer4'
INSTANCE_PURPOSE_INDEXER_STREAM_PRODUCER1 = 'indexer-stream-producer1'
INSTANCE_PURPOSE_INDEXER_STREAM_PRODUCER2 = 'indexer-stream-producer2'
INSTANCE_PURPOSE_INDEXER_LOAD_TEST = 'indexer-load-test'
INSTANCE_PURPOSE_INFORMATICA = 'informatica'
INSTANCE_PURPOSE_INGESTION_JOBS = 'ingestion-jobs'
INSTANCE_PURPOSE_INSIGHTS_APIS = 'insights-apis'
INSTANCE_PURPOSE_INSIGHTS_JOBS = 'insights-jobs'
INSTANCE_PURPOSE_KAFKA_COMPONENT = 'kafka-component'
INSTANCE_PURPOSE_TOKENS = 'tokens'
INSTANCE_PURPOSE_KUBERNETES_DEPLOYER = 'kubernetes-deploy'
INSTANCE_PURPOSE_LISTING_DEBUG = 'listing-pipeline-debug'
INSTANCE_PURPOSE_LISTING_EDITORS = 'listing-editors'
INSTANCE_PURPOSE_LISTINGS_NORMALIZATION = 'listings-normalization'
INSTANCE_PURPOSE_LISTINGS_NORMALIZATION_REALTIME = 'listings-normalization-realtime'
INSTANCE_PURPOSE_LISTING_SCHOOL = 'listing-school'
INSTANCE_PURPOSE_LISTINGS_SERVICE = 'listings-service'
INSTANCE_PURPOSE_LOCALES = 'locales'
INSTANCE_PURPOSE_MARKETING_CENTER = 'marketing-center'
INSTANCE_PURPOSE_MESSIER = 'messier'
INSTANCE_PURPOSE_MESSIER_INSTANT = 'messier-instant'
INSTANCE_PURPOSE_MONGO_BACKUP = 'mongo-backup'
INSTANCE_PURPOSE_NETWORK = 'network'
INSTANCE_PURPOSE_NOTIFICATION = 'notification'
INSTANCE_PURPOSE_NPM_ENTERPRISE = 'npm-enterprise'
INSTANCE_PURPOSE_OPENGROK = 'opengrok'
INSTANCE_PURPOSE_OPEN_HOUSE = 'open-house'
INSTANCE_PURPOSE_OPEN_HOUSE_JOBS = 'open-house-jobs'
INSTANCE_PURPOSE_PACKER = 'packer'
INSTANCE_PURPOSE_PDF_EXPORT = 'pdf-export'
INSTANCE_PURPOSE_PEOPLE = 'people'
INSTANCE_PURPOSE_PEOPLE_JOBS = 'people-jobs'
INSTANCE_PURPOSE_PERCOLATE_PROCESSOR = 'percolate-processor'
INSTANCE_PURPOSE_PERMISSIONS = 'permissions'
INSTANCE_PURPOSE_PHYSICAL_SIGNS = 'physical-signs'
INSTANCE_PURPOSE_PLATFORM = 'platform'
INSTANCE_PURPOSE_PLATFORM_SEARCH = 'platform-search'
INSTANCE_PURPOSE_PROMOTE_JOBS = 'promote-jobs'
INSTANCE_PURPOSE_PROPERTIES = 'properties'
INSTANCE_PURPOSE_REDIRECT = 'redirect'
INSTANCE_PURPOSE_RENORMALIZE_SERVICE = 'renormalize'
INSTANCE_PURPOSE_RESEARCH_ANALYTICS = 'research-analytics'
INSTANCE_PURPOSE_RESEARCH_APIS = 'research-apis'
INSTANCE_PURPOSE_RESEARCH_JOBS = 'research-jobs'
INSTANCE_PURPOSE_SAVED_SEARCH = 'saved-search'
INSTANCE_PURPOSE_SAVED_SEARCHES = 'saved-searches'
INSTANCE_PURPOSE_SAVED_SEARCHES2 = 'saved-searches2'
INSTANCE_PURPOSE_SCHOOL = 'school'
INSTANCE_PURPOSE_SEARCH_FILTERS_CONFIG = 'search-filters-config'
INSTANCE_PURPOSE_SEARCH_UI_BUILDER = 'search-ui-builder'
INSTANCE_PURPOSE_SEARCHER = 'searcher'
INSTANCE_PURPOSE_SEARCHER2 = 'searcher2'
INSTANCE_PURPOSE_SEARCHER3 = 'searcher3'
INSTANCE_PURPOSE_SEARCHER4 = 'searcher4'
INSTANCE_PURPOSE_SEARCHER_PARENT = 'searcher-parent'
INSTANCE_PURPOSE_SEARCH_QUERIES = 'search-queries'
INSTANCE_PURPOSE_SUGGESTIONS = 'suggestions'
INSTANCE_PURPOSE_SYNDICATION_AIRFLOW_WORKER = 'syndication-airflow-worker'
INSTANCE_PURPOSE_LISTINGS_EXPORTER_JOBS = 'listings-exporter-jobs'
INSTANCE_PURPOSE_GIS_SERVICE_EXPORTER_JOBS = 'gis-service-exporter-jobs'
INSTANCE_PURPOSE_TASKS = 'tasks'
INSTANCE_PURPOSE_TRANSIT = 'transit'
INSTANCE_PURPOSE_TEST = 'launch-test'  # Use this one for instance launch testing
INSTANCE_PURPOSE_TESTING = 'testing'
INSTANCE_PURPOSE_TOURS_MIGRATORS_SINGLETON = 'tours-migrators-singleton'
INSTANCE_PURPOSE_TOURSHEET = 'toursheet'
INSTANCE_PURPOSE_VPN = 'vpn'
INSTANCE_PURPOSE_WORKSPACE = 'workspace'
INSTANCE_PURPOSE_ZOOKEEPER = 'zookeeper'

KNOWN_INSTANCE_PURPOSES = frozenset((
  INSTANCE_PURPOSE_ACTIVITY_FEED,
  INSTANCE_PURPOSE_ACTIVITY_JOBS,
  INSTANCE_PURPOSE_ADDRESS_LOOKUP_SERVICE,
  INSTANCE_PURPOSE_AIRFLOW_SCHEDULER,
  INSTANCE_PURPOSE_AIRFLOW_WORKER,
  INSTANCE_PURPOSE_AIRFLOW_WORKER2,
  INSTANCE_PURPOSE_AIRFLOW_WORKER3,
  INSTANCE_PURPOSE_ASYNC_IMAGE_PROCESSOR,
  INSTANCE_PURPOSE_BASTION,
  INSTANCE_PURPOSE_BUILDINGS,
  INSTANCE_PURPOSE_BUILDING_EDITORS,
  INSTANCE_PURPOSE_CI,
  INSTANCE_PURPOSE_COMPASS_QIC,
  INSTANCE_PURPOSE_COMMS_CONTACTS_JOBS,
  INSTANCE_PURPOSE_CONTACT_EMAIL,
  INSTANCE_PURPOSE_CONTACTS,
  INSTANCE_PURPOSE_CREATIVE_STUDIO,
  INSTANCE_PURPOSE_DATA_APIS,
  INSTANCE_PURPOSE_DATA_DB,
  INSTANCE_PURPOSE_DATA_INTEGRATION_TEST,
  INSTANCE_PURPOSE_DATA_MONGO_BACKUP,
  INSTANCE_PURPOSE_DB,
  INSTANCE_PURPOSE_DEALS,
  INSTANCE_PURPOSE_DEALS_JOBS,
  INSTANCE_PURPOSE_DEALS_MIGRATORS_SINGLETON,
  INSTANCE_PURPOSE_DEMO,
  INSTANCE_PURPOSE_DEMO_POOL,
  INSTANCE_PURPOSE_DEPLOYER,
  INSTANCE_PURPOSE_DEVOPS,
  INSTANCE_PURPOSE_DOCUMENTS,
  INSTANCE_PURPOSE_EDITABLE_ACTIVITY,
  INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER,
  INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER2,
  INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER3,
  INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER2_LOAD_TEST,
  INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER_LOAD_TEST,
  INSTANCE_PURPOSE_ELASTIC_SEARCH_SEARCHER,
  INSTANCE_PURPOSE_ELASTIC_SEARCH_SEARCHER2,
  INSTANCE_PURPOSE_EMAIL_CAMPAIGN,
  INSTANCE_PURPOSE_EMR_JOBS,
  INSTANCE_PURPOSE_EVENTS_APIS,
  INSTANCE_PURPOSE_FIVETRAN_BASTION,
  INSTANCE_PURPOSE_FF_TUNNELS,
  INSTANCE_PURPOSE_FRONTEND,
  INSTANCE_PURPOSE_FRONTEND_CONFIG,
  INSTANCE_PURPOSE_FRONTEND_PROXY,
  INSTANCE_PURPOSE_FRONTEND_TIER1,
  INSTANCE_PURPOSE_FTP_TO_S3_MIRROR,
  INSTANCE_PURPOSE_GENERIC_JOBS,
  INSTANCE_PURPOSE_GEOCODING,
  INSTANCE_PURPOSE_GEOCODING_SERVICE,
  INSTANCE_PURPOSE_GERRIT,
  INSTANCE_PURPOSE_GI_APPS,
  INSTANCE_PURPOSE_GIS_SERVICE,
  INSTANCE_PURPOSE_GIS_SERVICE_TEST,
  INSTANCE_PURPOSE_GIS_IMPORTER,
  INSTANCE_PURPOSE_IAM_SSH,
  INSTANCE_PURPOSE_HELPER_TOOLS,
  INSTANCE_PURPOSE_IDENTITY,
  INSTANCE_PURPOSE_IMAGE_PROCESSOR,
  INSTANCE_PURPOSE_IMAGE_RESPONSE_PROCESSOR,
  INSTANCE_PURPOSE_INDEXER,
  INSTANCE_PURPOSE_INDEXER2,
  INSTANCE_PURPOSE_INDEXER3,
  INSTANCE_PURPOSE_INDEXER3_LOAD_TEST,
  INSTANCE_PURPOSE_INDEXER4,
  INSTANCE_PURPOSE_INDEXER_STREAM_PRODUCER1,
  INSTANCE_PURPOSE_INDEXER_STREAM_PRODUCER2,
  INSTANCE_PURPOSE_INDEXER_LOAD_TEST,
  INSTANCE_PURPOSE_INFORMATICA,
  INSTANCE_PURPOSE_INGESTION_JOBS,
  INSTANCE_PURPOSE_INSIGHTS_APIS,
  INSTANCE_PURPOSE_INSIGHTS_JOBS,
  INSTANCE_PURPOSE_KAFKA_COMPONENT,
  INSTANCE_PURPOSE_TOKENS,
  INSTANCE_PURPOSE_KUBERNETES_DEPLOYER,
  INSTANCE_PURPOSE_LISTING_DEBUG,
  INSTANCE_PURPOSE_LISTING_EDITORS,
  INSTANCE_PURPOSE_LISTINGS_NORMALIZATION,
  INSTANCE_PURPOSE_LISTINGS_NORMALIZATION_REALTIME,
  INSTANCE_PURPOSE_LISTING_SCHOOL,
  INSTANCE_PURPOSE_LISTINGS_SERVICE,
  INSTANCE_PURPOSE_LOCALES,
  INSTANCE_PURPOSE_MARKETING_CENTER,
  INSTANCE_PURPOSE_MESSIER,
  INSTANCE_PURPOSE_MESSIER_INSTANT,
  INSTANCE_PURPOSE_MONGO_BACKUP,
  INSTANCE_PURPOSE_NETWORK,
  INSTANCE_PURPOSE_NOTIFICATION,
  INSTANCE_PURPOSE_NPM_ENTERPRISE,
  INSTANCE_PURPOSE_OPENGROK,
  INSTANCE_PURPOSE_OPEN_HOUSE,
  INSTANCE_PURPOSE_OPEN_HOUSE_JOBS,
  INSTANCE_PURPOSE_PACKER,
  INSTANCE_PURPOSE_PDF_EXPORT,
  INSTANCE_PURPOSE_PEOPLE,
  INSTANCE_PURPOSE_PEOPLE_JOBS,
  INSTANCE_PURPOSE_PERCOLATE_PROCESSOR,
  INSTANCE_PURPOSE_PERMISSIONS,
  INSTANCE_PURPOSE_PHYSICAL_SIGNS,
  INSTANCE_PURPOSE_PLATFORM,
  INSTANCE_PURPOSE_PLATFORM_SEARCH,
  INSTANCE_PURPOSE_PROMOTE_JOBS,
  INSTANCE_PURPOSE_PROPERTIES,
  INSTANCE_PURPOSE_REDIRECT,
  INSTANCE_PURPOSE_RENORMALIZE_SERVICE,
  INSTANCE_PURPOSE_RESEARCH_ANALYTICS,
  INSTANCE_PURPOSE_RESEARCH_APIS,
  INSTANCE_PURPOSE_RESEARCH_JOBS,
  INSTANCE_PURPOSE_SAVED_SEARCH,
  INSTANCE_PURPOSE_SAVED_SEARCHES,
  INSTANCE_PURPOSE_SAVED_SEARCHES2,
  INSTANCE_PURPOSE_SCHOOL,
  INSTANCE_PURPOSE_SEARCH_FILTERS_CONFIG,
  INSTANCE_PURPOSE_SEARCH_UI_BUILDER,
  INSTANCE_PURPOSE_SEARCHER,
  INSTANCE_PURPOSE_SEARCHER2,
  INSTANCE_PURPOSE_SEARCHER3,
  INSTANCE_PURPOSE_SEARCHER4,
  INSTANCE_PURPOSE_SEARCHER_PARENT,
  INSTANCE_PURPOSE_SEARCH_QUERIES,
  INSTANCE_PURPOSE_SUGGESTIONS,
  INSTANCE_PURPOSE_SYNDICATION_AIRFLOW_WORKER,
  INSTANCE_PURPOSE_LISTINGS_EXPORTER_JOBS,
  INSTANCE_PURPOSE_GIS_SERVICE_EXPORTER_JOBS,
  INSTANCE_PURPOSE_TASKS,
  INSTANCE_PURPOSE_TRANSIT,
  INSTANCE_PURPOSE_TEST,
  INSTANCE_PURPOSE_TESTING,
  INSTANCE_PURPOSE_TOURS_MIGRATORS_SINGLETON,
  INSTANCE_PURPOSE_TOURSHEET,
  INSTANCE_PURPOSE_VPN,
  INSTANCE_PURPOSE_WORKSPACE,
  INSTANCE_PURPOSE_ZOOKEEPER,
))

# IAM Roles

IAM_ROLE_ACTIVITY_FEED_PRODUCTION = 'ActivityFeedProduction'
IAM_ROLE_ACTIVITY_FEED_STAGING = 'ActivityFeedStaging'
IAM_ROLE_ACTIVITY_JOBS_PRODUCTION = 'ActivityJobsProduction'
IAM_ROLE_ACTIVITY_JOBS_STAGING = 'ActivityJobsStaging'
IAM_ROLE_ADDRESS_LOOKUP_SERVICE_PRODUCTION = 'AddressLookupProduction'
IAM_ROLE_ADDRESS_LOOKUP_SERVICE_STAGING = 'AddressLookupStaging'
IAM_ROLE_AIRFLOW_SCHEDULER_PRODUCTION = 'AirflowSchedulerProduction'
IAM_ROLE_AIRFLOW_SCHEDULER_STAGING = 'AirflowSchedulerStaging'
IAM_ROLE_AIRFLOW_WORKER_PRODUCTION = 'AirflowWorkerProduction'
IAM_ROLE_AIRFLOW_WORKER_STAGING = 'AirflowWorkerStaging'
IAM_ROLE_BASTION = 'Bastion'
IAM_ROLE_BUILDINGS_PRODUCTION = 'BuildingsProduction'
IAM_ROLE_BUILDINGS_STAGING = 'BuildingsStaging'
IAM_ROLE_BUILDING_EDITORS_PRODUCTION = 'BuildingEditorsProduction'
IAM_ROLE_BUILDING_EDITORS_STAGING = 'BuildingEditorsStaging'
IAM_ROLE_BUILDINGS_DEVELOPMENT = 'BuildingsDevelopment'
IAM_ROLE_CLOUD_TESTING = 'CloudTestingDevelopment'
IAM_ROLE_COMPASS_QIC_STAGING = 'CompassQICStaging'
IAM_ROLE_COMPASS_QIC_PRODUCTION = 'CompassQICProduction'
IAM_ROLE_COMPASS_QIC_DEVELOPMENT = 'CompassQICDevelopment'
IAM_ROLE_COMMS_CONTACTS_JOBS_PRODUCTION = 'CommsContactsJobsProduction'
IAM_ROLE_COMMS_CONTACTS_JOBS_STAGING = 'CommsContactsJobsStaging'
IAM_ROLE_CONTACT_EMAIL_DEVELOPMENT = 'ContactEmailDevelopment'
IAM_ROLE_CONTACT_EMAIL_PRODUCTION = 'ContactEmailProduction'
IAM_ROLE_CONTACT_EMAIL_STAGING = 'ContactEmailStaging'
IAM_ROLE_CONTACTS_DEVELOPMENT = 'ContactsDevelopment'
IAM_ROLE_CONTACTS_PRODUCTION = 'ContactsProduction'
IAM_ROLE_CONTACTS_STAGING = 'ContactsStaging'
IAM_ROLE_CREATIVE_STUDIO_DEVELOPMENT = 'CreativeStudioDevelopment'
IAM_ROLE_CREATIVE_STUDIO_PRODUCTION = 'CreativeStudioProduction'
IAM_ROLE_CREATIVE_STUDIO_STAGING = 'CreativeStudioStaging'
IAM_ROLE_DATA_APIS_PRODUCTION = 'DataApisProduction'
IAM_ROLE_DATA_APIS_STAGING = 'DataApisStaging'
IAM_ROLE_DATA_INTEGRATION_TEST_STAGING = 'DataIntegrationTestStaging'
IAM_ROLE_DATA_MONGO_BACKUP_PRODUCTION = 'DataMongoBackupProduction'
IAM_ROLE_DATA_MONGO_BACKUP_STAGING = 'DataMongoBackupStaging'
IAM_ROLE_DATA_MONGO_PRODUCTION = 'DataMongoProduction'
IAM_ROLE_DATA_MONGO_STAGING = 'DataMongoStaging'
IAM_ROLE_DEALS_PRODUCTION = 'DealsProduction'
IAM_ROLE_DEALS_STAGING = 'DealsStaging'
IAM_ROLE_DEALS_JOBS_PRODUCTION = 'DealsJobsProduction'
IAM_ROLE_DEALS_JOBS_STAGING = 'DealsJobsStaging'
IAM_ROLE_DEALS_MIGRATORS_SINGLETON_PRODUCTION = 'DealsMigratorsSingletonProduction'
IAM_ROLE_DEALS_MIGRATORS_SINGLETON_STAGING = 'DealsMigratorsSingletonStaging'
IAM_ROLE_DEMO_POOL = 'DemoPool'
IAM_ROLE_DEPLOYER = 'JenkinsIndexerDeployer'
IAM_ROLE_DOCUMENTS_PRODUCTION = 'DocumentsProduction'
IAM_ROLE_DOCUMENTS_STAGING = 'DocumentsStaging'
IAM_ROLE_EDITABLE_ACTIVITY_DEVELOPMENT = 'EditableActivityDevelopment'
IAM_ROLE_EDITABLE_ACTIVITY_PRODUCTION = 'EditableActivityProduction'
IAM_ROLE_EDITABLE_ACTIVITY_STAGING = 'EditableActivityStaging'
IAM_ROLE_ELASTIC_SEARCH_INDEXER_PRODUCTION = 'IndexerProduction'
IAM_ROLE_ELASTIC_SEARCH_INDEXER_STAGING = 'IndexerStaging'
IAM_ROLE_ELASTIC_SEARCH_SEARCHER_PRODUCTION = 'SearcherProduction'
IAM_ROLE_ELASTIC_SEARCH_SEARCHER_STAGING = 'SearcherStaging'
IAM_ROLE_EMAIL_CAMPAIGN_PRODUCTION = 'EmailCampaignProduction'
IAM_ROLE_EMAIL_CAMPAIGN_STAGING = 'EmailCampaignStaging'
IAM_ROLE_EMR_JOBS_PRODUCTION = 'EmrJobsProduction'
IAM_ROLE_EMR_JOBS_STAGING = 'EmrJobsStaging'
IAM_ROLE_EVENTS_LOGGER_PRODUCTION = 'EventsLoggerProduction'
IAM_ROLE_EVENTS_LOGGER_STAGING = 'EventsLoggerStaging'
IAM_ROLE_FF_TUNNELS_DEVELOPMENT = 'TunnelsDevelopment'
IAM_ROLE_FRONTEND_DEVELOPMENT = 'FrontendDevelopment'
IAM_ROLE_FRONTEND_PRODUCTION = 'FrontendProduction'
IAM_ROLE_FRONTEND_STAGING = 'FrontendStaging'
IAM_ROLE_FRONTEND_CONFIG_PRODUCTION = 'FrontendConfigProduction'
IAM_ROLE_FRONTEND_CONFIG_STAGING = 'FrontendConfigStaging'
IAM_ROLE_FRONTEND_CONFIG_DEVELOPMENT = 'FrontendConfigDevelopment'
IAM_ROLE_FTP_TO_S3_MIRROR_PRODUCTION = 'FtpToS3MirrorProduction'
IAM_ROLE_FTP_TO_S3_MIRROR_STAGING = 'FtpToS3MirrorStaging'
IAM_ROLE_GENERIC_JOBS_PRODUCTION = 'GenericJobsProduction'
IAM_ROLE_GENERIC_JOBS_STAGING = 'GenericJobsStaging'
IAM_ROLE_GEOCODING_PRODUCTION = 'GeocodingProduction'
IAM_ROLE_GEOCODING_STAGING = 'GeocodingStaging'
IAM_ROLE_GEOCODING_SERVICE_PRODUCTION = 'GeocodingProduction'  # reusing the SG
IAM_ROLE_GEOCODING_SERVICE_STAGING = 'GeocodingStaging'
IAM_ROLE_GERRIT = 'Gerrit'
IAM_ROLE_GI_APPS_DEVELOPMENT = 'GiAppsDevelopment'
IAM_ROLE_GI_APPS_PRODUCTION = 'GiAppsProduction'
IAM_ROLE_GI_APPS_STAGING = 'GiAppsStaging'
IAM_ROLE_GIS_SERVICE_PRODUCTION = 'GisServiceProduction'
IAM_ROLE_GIS_SERVICE_STAGING = 'GisServiceStaging'
IAM_ROLE_GIS_SERVICE_DEVELOPMENT = 'GisServiceDevelopment'
IAM_ROLE_GIS_IMPORTER_STAGING = 'GisImporterStaging'
IAM_ROLE_GIS_IMPORTER_PRODUCTION = 'GisImporterProduction'
IAM_ROLE_GIS_SERVICE_TEST_STAGING = 'GisServiceTestStaging'
IAM_ROLE_GIS_SERVICE_TEST_PRODUCTION = 'GisServiceTestProduction'
IAM_ROLE_HELPER_TOOLS_PRODUCTION = 'HelperToolsProduction'
IAM_ROLE_HELPER_TOOLS_STAGING = 'HelperToolsStaging'
IAM_ROLE_IDENTITY_PRODUCTION = 'IdentityProduction'
IAM_ROLE_IDENTITY_STAGING = 'IdentityStaging'
IAM_ROLE_INDEXER_STREAM_PRODUCER_PRODUCTION1 = 'IndexerStreamProducerProduction1'
IAM_ROLE_INDEXER_STREAM_PRODUCER_PRODUCTION2 = 'IndexerStreamProducerProduction2'
IAM_ROLE_INDEXER_STREAM_PRODUCER_STAGING1 = 'IndexerStreamProducerStaging1'
IAM_ROLE_INDEXER_STREAM_PRODUCER_STAGING2 = 'IndexerStreamProducerStaging2'
IAM_ROLE_IMAGE_PROCESSOR_PRODUCTION = 'ImageProcessorProduction'
IAM_ROLE_IMAGE_PROCESSOR_STAGING = 'ImageProcessorStaging'
IAM_ROLE_IMAGE_RESPONSE_PROCESSOR_PRODUCTION = 'ImageResponseProcessorProduction'
IAM_ROLE_IMAGE_RESPONSE_PROCESSOR_STAGING = 'ImageResponseProcessorStaging'
IAM_ROLE_INFORMATICA_PRODUCTION = 'InformaticaProduction'
IAM_ROLE_INFORMATICA_STAGING = 'InformaticaStaging'
IAM_ROLE_INGESTION_JOBS_PRODUCTION = 'IngestionJobsProduction'
IAM_ROLE_INGESTION_JOBS_STAGING = 'IngestionJobsStaging'
IAM_ROLE_INSIGHTS_APIS_PRODUCTION = 'InsightsApisProduction'
IAM_ROLE_INSIGHTS_APIS_STAGING = 'InsightsApisStaging'
IAM_ROLE_INSIGHTS_JOBS_PRODUCTION = 'InsightsJobsProduction'
IAM_ROLE_INSIGHTS_JOBS_STAGING = 'InsightsJobsStaging'
IAM_ROLE_TOKENS_DEVELOPMENT = 'TokensDevelopment'
IAM_ROLE_TOKENS_PRODUCTION = 'TokensProduction'
IAM_ROLE_TOKENS_STAGING = 'TokensStaging'
IAM_ROLE_KUBERNETES_DEPLOYER = 'JenkinsKubernetesDeployer'
IAM_ROLE_LISTING_EDITORS_PRODUCTION = 'ListingEditorsProduction'
IAM_ROLE_LISTING_EDITORS_STAGING = 'ListingEditorsStaging'
IAM_ROLE_LISTINGS_NORMALIZATION_PRODUCTION = 'ListingsNormalizationProduction'
IAM_ROLE_LISTINGS_NORMALIZATION_STAGING = 'ListingsNormalizationStaging'
IAM_ROLE_LISTINGS_PRODUCTION = 'ListingsProduction'
IAM_ROLE_LISTINGS_STAGING = 'ListingsStaging'
IAM_ROLE_LOCALES_PRODUCTION = 'LocalesProduction'
IAM_ROLE_LOCALES_STAGING = 'LocalesStaging'
IAM_ROLE_MARKETING_CENTER_PRODUCTION = 'MarketingCenterProduction'
IAM_ROLE_MARKETING_CENTER_STAGING = 'MarketingCenterStaging'
IAM_ROLE_MESSIER_DEVELOPMENT = 'MessierDevelopment'
IAM_ROLE_MESSIER_PRODUCTION = 'MessierProduction'
IAM_ROLE_MESSIER_STAGING = 'MessierStaging'
IAM_ROLE_MONGO_BACKUP_PRODUCTION = 'MongoBackupProduction'
IAM_ROLE_MONGO_BACKUP_STAGING = 'MongoBackupStaging'
IAM_ROLE_MONGO_PRODUCTION = 'MongoProduction'
IAM_ROLE_MONGO_STAGING = 'MongoStaging'
IAM_ROLE_NETWORK_DEVELOPMENT = 'NetworkDevelopment'
IAM_ROLE_NETWORK_PRODUCTION = 'NetworkProduction'
IAM_ROLE_NETWORK_STAGING = 'NetworkStaging'
IAM_ROLE_NOTIFICATION_PRODUCTION = 'NotificationProduction'
IAM_ROLE_NOTIFICATION_STAGING = 'NotificationStaging'
IAM_ROLE_NPM = 'NPM'
IAM_ROLE_OPENGROK = 'OpenGrok'
IAM_ROLE_OPEN_HOUSE_DEVELOPMENT = 'OpenHouseDevelopment'
IAM_ROLE_OPEN_HOUSE_STAGING = 'OpenHouseStaging'
IAM_ROLE_OPEN_HOUSE_PRODUCTION = 'OpenHouseProduction'
IAM_ROLE_OPEN_HOUSE_JOBS_DEVELOPMENT = 'OpenHouseJobsDevelopment'
IAM_ROLE_OPEN_HOUSE_JOBS_STAGING = 'OpenHouseJobsStaging'
IAM_ROLE_OPEN_HOUSE_JOBS_PRODUCTION = 'OpenHouseJobsProduction'
IAM_ROLE_PACKER = 'Packer'
IAM_ROLE_PDF_EXPORT_PRODUCTION = 'PdfExportProduction'
IAM_ROLE_PDF_EXPORT_STAGING = 'PdfExportStaging'
IAM_ROLE_PEOPLE_JOBS_PRODUCTION = 'PeopleJobsProduction'
IAM_ROLE_PEOPLE_JOBS_STAGING = 'PeopleJobsStaging'
IAM_ROLE_PEOPLE_PRODUCTION = 'PeopleProduction'
IAM_ROLE_PEOPLE_STAGING = 'PeopleStaging'
IAM_ROLE_PERCOLATE_PROCESSOR_STAGING = 'PercolateProcessorStaging'
IAM_ROLE_PERCOLATE_PROCESSOR_PRODUCTION = 'PercolateProcessorProduction'
IAM_ROLE_PERMISSIONS_DEVELOPMENT = 'PermissionsDevelopment'
IAM_ROLE_PERMISSIONS_PRODUCTION = 'PermissionsProduction'
IAM_ROLE_PERMISSIONS_STAGING = 'PermissionsStaging'
IAM_ROLE_PHYSICAL_SIGNS_PRODUCTION = 'PhysicalSignsProduction'
IAM_ROLE_PHYSICAL_SIGNS_STAGING = 'PhysicalSignsStaging'
IAM_ROLE_PLATFORM_PRODUCTION = 'PlatformProduction'
IAM_ROLE_PLATFORM_STAGING = 'PlatformStaging'
IAM_ROLE_PROMOTE_JOBS_PRODUCTION = 'PromoteJobsProduction'
IAM_ROLE_PROMOTE_JOBS_STAGING = 'PromoteJobsStaging'
IAM_ROLE_PROPERTIES_PRODUCTION = 'PropertiesProduction'
IAM_ROLE_PROPERTIES_STAGING = 'PropertiesStaging'
IAM_ROLE_REDIRECT = 'Redirect'
IAM_ROLE_RENORMALIZE_SERVICE_PRODUCTION = 'RenormalizeProduction'
IAM_ROLE_RENORMALIZE_SERVICE_STAGING = 'RenormalizeStaging'
IAM_ROLE_RESEARCH_ANALYTICAL_FRAMEWORK_PRODUCTION = 'ResearchAnalyticalFrameworkProduction'
IAM_ROLE_RESEARCH_APIS_PRODUCTION = 'ResearchApisProduction'
IAM_ROLE_RESEARCH_APIS_STAGING = 'ResearchApisStaging'
IAM_ROLE_RESEARCH_JOBS_PRODUCTION = 'ResearchJobsProduction'
IAM_ROLE_RESEARCH_JOBS_STAGING = 'ResearchJobsStaging'
IAM_ROLE_SAVED_SEARCH_DEVELOPMENT = 'SavedSearchDevelopment'
IAM_ROLE_SAVED_SEARCH_PRODUCTION = 'SavedSearchProduction'
IAM_ROLE_SAVED_SEARCH_STAGING = 'SavedSearchStaging'
IAM_ROLE_SAVED_SEARCHES_PRODUCTION = 'SavedSearchesProduction'
IAM_ROLE_SAVED_SEARCHES_STAGING = 'SavedSearchesStaging'
IAM_ROLE_SCHOOL_PRODUCTION = 'SchoolProduction'
IAM_ROLE_SCHOOL_STAGING = 'SchoolStaging'
IAM_ROLE_SEARCH_FILTERS_CONFIG_DEVELOPMENT = 'SearchFiltersConfigDevelopment'
IAM_ROLE_SEARCH_FILTERS_CONFIG_PRODUCTION = 'SearchFiltersConfigProduction'
IAM_ROLE_SEARCH_FILTERS_CONFIG_STAGING = 'SearchFiltersConfigStaging'
IAM_ROLE_SEARCH_UI_BUILDER_DEVELOPMENT = 'SearchUiBuilderDevelopment'
IAM_ROLE_SEARCH_UI_BUILDER_PRODUCTION = 'SearchUiBuilderProduction'
IAM_ROLE_SEARCH_UI_BUILDER_STAGING = 'SearchUiBuilderStaging'
IAM_ROLE_SEARCH_QUERIES_DEVELOPMENT = 'SearchQueriesDevelopment'
IAM_ROLE_SEARCH_QUERIES_PRODUCTION = 'SearchQueriesProduction'
IAM_ROLE_SEARCH_QUERIES_STAGING = 'SearchQueriesStaging'
IAM_ROLE_SEARCHER_PARENT_PRODUCTION = 'SearcherParentProduction'
IAM_ROLE_SEARCHER_PARENT_STAGING = 'SearcherParentStaging'
IAM_ROLE_SUGGESTIONS_DEVELOPMENT = 'SuggestionsDevelopment'
IAM_ROLE_SUGGESTIONS_PRODUCTION = 'SuggestionsProduction'
IAM_ROLE_SUGGESTIONS_STAGING = 'SuggestionsStaging'
IAM_ROLE_SYNDICATION_AIRFLOW_WORKER_PRODUCTION = 'SyndicationAirflowWorkerProduction'
IAM_ROLE_SYNDICATION_AIRFLOW_WORKER_STAGING = 'SyndicationAirflowWorkerStaging'
IAM_ROLE_TASKS_PRODUCTION = 'TasksProduction'
IAM_ROLE_TASKS_STAGING = 'TasksStaging'
IAM_ROLE_TOURS_MIGRATORS_SINGLETON_PRODUCTION = 'ToursMigratorsSingletonProduction'
IAM_ROLE_TOURS_MIGRATORS_SINGLETON_STAGING = 'ToursMigratorsSingletonStaging'
IAM_ROLE_TOURSHEET_PRODUCTION = 'ToursheetProduction'
IAM_ROLE_TOURSHEET_STAGING = 'ToursheetStaging'
IAM_ROLE_TRANSIT_PRODUCTION = 'TransitProduction'
IAM_ROLE_TRANSIT_STAGING = 'TransitStaging'
IAM_ROLE_LISTINGS_EXPORTER_JOBS_PRODUCTION = 'ListingsExporterJobsProduction'
IAM_ROLE_GIS_SERVICE_EXPORTER_JOBS_PRODUCTION = 'GisServiceExporterJobsProduction'
IAM_ROLE_LISTINGS_EXPORTER_JOBS_STAGING = 'ListingsExporterJobsStaging'
IAM_ROLE_GIS_SERVICE_EXPORTER_JOBS_STAGING = 'GisServiceExporterJobsStaging'
IAM_ROLE_WORKSPACE_PRODUCTION = 'WorkspaceProduction'
IAM_ROLE_WORKSPACE_STAGING = 'WorkspaceStaging'
IAM_ROLE_ZOOKEEPER = 'Zookeeper'


KNOWN_IAM_ROLES = frozenset((
  IAM_ROLE_ACTIVITY_FEED_PRODUCTION,
  IAM_ROLE_ACTIVITY_FEED_STAGING,
  IAM_ROLE_ACTIVITY_JOBS_PRODUCTION,
  IAM_ROLE_ACTIVITY_JOBS_STAGING,
  IAM_ROLE_ADDRESS_LOOKUP_SERVICE_PRODUCTION,
  IAM_ROLE_ADDRESS_LOOKUP_SERVICE_STAGING,
  IAM_ROLE_AIRFLOW_SCHEDULER_PRODUCTION,
  IAM_ROLE_AIRFLOW_SCHEDULER_STAGING,
  IAM_ROLE_AIRFLOW_WORKER_PRODUCTION,
  IAM_ROLE_AIRFLOW_WORKER_STAGING,
  IAM_ROLE_BASTION,
  IAM_ROLE_BUILDINGS_PRODUCTION,
  IAM_ROLE_BUILDINGS_STAGING,
  IAM_ROLE_BUILDING_EDITORS_PRODUCTION,
  IAM_ROLE_BUILDING_EDITORS_STAGING,
  IAM_ROLE_COMPASS_QIC_DEVELOPMENT,
  IAM_ROLE_COMPASS_QIC_STAGING,
  IAM_ROLE_COMMS_CONTACTS_JOBS_PRODUCTION,
  IAM_ROLE_CONTACT_EMAIL_DEVELOPMENT,
  IAM_ROLE_CONTACT_EMAIL_PRODUCTION,
  IAM_ROLE_CONTACT_EMAIL_STAGING,
  IAM_ROLE_CONTACTS_DEVELOPMENT,
  IAM_ROLE_CONTACTS_PRODUCTION,
  IAM_ROLE_CONTACTS_STAGING,
  IAM_ROLE_CLOUD_TESTING,
  IAM_ROLE_COMMS_CONTACTS_JOBS_PRODUCTION,
  IAM_ROLE_COMMS_CONTACTS_JOBS_STAGING,
  IAM_ROLE_CREATIVE_STUDIO_DEVELOPMENT,
  IAM_ROLE_CREATIVE_STUDIO_PRODUCTION,
  IAM_ROLE_CREATIVE_STUDIO_STAGING,
  IAM_ROLE_DATA_APIS_PRODUCTION,
  IAM_ROLE_DATA_APIS_STAGING,
  IAM_ROLE_DATA_INTEGRATION_TEST_STAGING,
  IAM_ROLE_DATA_MONGO_BACKUP_PRODUCTION,
  IAM_ROLE_DATA_MONGO_BACKUP_STAGING,
  IAM_ROLE_DATA_MONGO_PRODUCTION,
  IAM_ROLE_DATA_MONGO_STAGING,
  IAM_ROLE_DEALS_PRODUCTION,
  IAM_ROLE_DEALS_STAGING,
  IAM_ROLE_DEALS_JOBS_PRODUCTION,
  IAM_ROLE_DEALS_JOBS_STAGING,
  IAM_ROLE_DEALS_MIGRATORS_SINGLETON_PRODUCTION,
  IAM_ROLE_DEALS_MIGRATORS_SINGLETON_STAGING,
  IAM_ROLE_DEMO_POOL,
  IAM_ROLE_DEPLOYER,
  IAM_ROLE_DOCUMENTS_PRODUCTION,
  IAM_ROLE_DOCUMENTS_STAGING,
  IAM_ROLE_EDITABLE_ACTIVITY_DEVELOPMENT,
  IAM_ROLE_EDITABLE_ACTIVITY_PRODUCTION,
  IAM_ROLE_EDITABLE_ACTIVITY_STAGING,
  IAM_ROLE_ELASTIC_SEARCH_INDEXER_PRODUCTION,
  IAM_ROLE_ELASTIC_SEARCH_INDEXER_STAGING,
  IAM_ROLE_ELASTIC_SEARCH_SEARCHER_PRODUCTION,
  IAM_ROLE_ELASTIC_SEARCH_SEARCHER_STAGING,
  IAM_ROLE_EMAIL_CAMPAIGN_PRODUCTION,
  IAM_ROLE_EMAIL_CAMPAIGN_STAGING,
  IAM_ROLE_EMR_JOBS_PRODUCTION,
  IAM_ROLE_EMR_JOBS_STAGING,
  IAM_ROLE_EVENTS_LOGGER_PRODUCTION,
  IAM_ROLE_EVENTS_LOGGER_STAGING,
  IAM_ROLE_FF_TUNNELS_DEVELOPMENT,
  IAM_ROLE_FRONTEND_DEVELOPMENT,
  IAM_ROLE_FRONTEND_PRODUCTION,
  IAM_ROLE_FRONTEND_STAGING,
  IAM_ROLE_FRONTEND_CONFIG_PRODUCTION,
  IAM_ROLE_FRONTEND_CONFIG_STAGING,
  IAM_ROLE_FRONTEND_CONFIG_DEVELOPMENT,
  IAM_ROLE_FTP_TO_S3_MIRROR_PRODUCTION,
  IAM_ROLE_FTP_TO_S3_MIRROR_STAGING,
  IAM_ROLE_GENERIC_JOBS_PRODUCTION,
  IAM_ROLE_GENERIC_JOBS_STAGING,
  IAM_ROLE_GEOCODING_PRODUCTION,
  IAM_ROLE_GEOCODING_STAGING,
  IAM_ROLE_GEOCODING_SERVICE_PRODUCTION,
  IAM_ROLE_GEOCODING_SERVICE_STAGING,
  IAM_ROLE_GERRIT,
  IAM_ROLE_GI_APPS_DEVELOPMENT,
  IAM_ROLE_GI_APPS_PRODUCTION,
  IAM_ROLE_GI_APPS_STAGING,
  IAM_ROLE_GIS_SERVICE_PRODUCTION,
  IAM_ROLE_GIS_SERVICE_STAGING,
  IAM_ROLE_GIS_SERVICE_DEVELOPMENT,
  IAM_ROLE_GIS_IMPORTER_STAGING,
  IAM_ROLE_GIS_IMPORTER_PRODUCTION,
  IAM_ROLE_GIS_SERVICE_TEST_STAGING,
  IAM_ROLE_GIS_SERVICE_TEST_PRODUCTION,
  IAM_ROLE_HELPER_TOOLS_PRODUCTION,
  IAM_ROLE_HELPER_TOOLS_STAGING,
  IAM_ROLE_IDENTITY_PRODUCTION,
  IAM_ROLE_INDEXER_STREAM_PRODUCER_PRODUCTION1,
  IAM_ROLE_INDEXER_STREAM_PRODUCER_PRODUCTION2,
  IAM_ROLE_INDEXER_STREAM_PRODUCER_STAGING1,
  IAM_ROLE_INDEXER_STREAM_PRODUCER_STAGING2,
  IAM_ROLE_IDENTITY_STAGING,
  IAM_ROLE_IMAGE_PROCESSOR_PRODUCTION,
  IAM_ROLE_IMAGE_PROCESSOR_STAGING,
  IAM_ROLE_IMAGE_RESPONSE_PROCESSOR_PRODUCTION,
  IAM_ROLE_IMAGE_RESPONSE_PROCESSOR_STAGING,
  IAM_ROLE_INFORMATICA_PRODUCTION,
  IAM_ROLE_INFORMATICA_STAGING,
  IAM_ROLE_INGESTION_JOBS_PRODUCTION,
  IAM_ROLE_INGESTION_JOBS_STAGING,
  IAM_ROLE_INSIGHTS_APIS_PRODUCTION,
  IAM_ROLE_INSIGHTS_APIS_STAGING,
  IAM_ROLE_INSIGHTS_JOBS_PRODUCTION,
  IAM_ROLE_INSIGHTS_JOBS_STAGING,
  IAM_ROLE_TOKENS_DEVELOPMENT,
  IAM_ROLE_TOKENS_PRODUCTION,
  IAM_ROLE_TOKENS_STAGING,
  IAM_ROLE_LISTING_EDITORS_PRODUCTION,
  IAM_ROLE_LISTING_EDITORS_STAGING,
  IAM_ROLE_LISTINGS_NORMALIZATION_PRODUCTION,
  IAM_ROLE_LISTINGS_NORMALIZATION_STAGING,
  IAM_ROLE_LISTINGS_PRODUCTION,
  IAM_ROLE_LISTINGS_STAGING,
  IAM_ROLE_LOCALES_PRODUCTION,
  IAM_ROLE_LOCALES_STAGING,
  IAM_ROLE_MARKETING_CENTER_PRODUCTION,
  IAM_ROLE_MARKETING_CENTER_STAGING,
  IAM_ROLE_MESSIER_DEVELOPMENT,
  IAM_ROLE_MESSIER_PRODUCTION,
  IAM_ROLE_MESSIER_STAGING,
  IAM_ROLE_MONGO_BACKUP_PRODUCTION,
  IAM_ROLE_MONGO_BACKUP_STAGING,
  IAM_ROLE_MONGO_PRODUCTION,
  IAM_ROLE_MONGO_STAGING,
  IAM_ROLE_NETWORK_DEVELOPMENT,
  IAM_ROLE_NETWORK_PRODUCTION,
  IAM_ROLE_NETWORK_STAGING,
  IAM_ROLE_NOTIFICATION_PRODUCTION,
  IAM_ROLE_NOTIFICATION_STAGING,
  IAM_ROLE_NPM,
  IAM_ROLE_OPENGROK,
  IAM_ROLE_OPEN_HOUSE_DEVELOPMENT,
  IAM_ROLE_OPEN_HOUSE_STAGING,
  IAM_ROLE_OPEN_HOUSE_PRODUCTION,
  IAM_ROLE_OPEN_HOUSE_JOBS_DEVELOPMENT,
  IAM_ROLE_OPEN_HOUSE_JOBS_STAGING,
  IAM_ROLE_OPEN_HOUSE_JOBS_PRODUCTION,
  IAM_ROLE_PACKER,
  IAM_ROLE_PDF_EXPORT_PRODUCTION,
  IAM_ROLE_PDF_EXPORT_STAGING,
  IAM_ROLE_PEOPLE_JOBS_PRODUCTION,
  IAM_ROLE_PEOPLE_JOBS_STAGING,
  IAM_ROLE_PEOPLE_PRODUCTION,
  IAM_ROLE_PEOPLE_STAGING,
  IAM_ROLE_PERCOLATE_PROCESSOR_STAGING,
  IAM_ROLE_PERCOLATE_PROCESSOR_PRODUCTION,
  IAM_ROLE_PERMISSIONS_DEVELOPMENT,
  IAM_ROLE_PERMISSIONS_PRODUCTION,
  IAM_ROLE_PERMISSIONS_STAGING,
  IAM_ROLE_PHYSICAL_SIGNS_PRODUCTION,
  IAM_ROLE_PHYSICAL_SIGNS_STAGING,
  IAM_ROLE_PLATFORM_PRODUCTION,
  IAM_ROLE_PLATFORM_STAGING,
  IAM_ROLE_PROPERTIES_PRODUCTION,
  IAM_ROLE_PROPERTIES_STAGING,
  IAM_ROLE_REDIRECT,
  IAM_ROLE_RESEARCH_ANALYTICAL_FRAMEWORK_PRODUCTION,
  IAM_ROLE_RESEARCH_APIS_PRODUCTION,
  IAM_ROLE_RESEARCH_APIS_STAGING,
  IAM_ROLE_RESEARCH_JOBS_PRODUCTION,
  IAM_ROLE_RESEARCH_JOBS_STAGING,
  IAM_ROLE_SAVED_SEARCH_DEVELOPMENT,
  IAM_ROLE_SAVED_SEARCH_PRODUCTION,
  IAM_ROLE_SAVED_SEARCH_STAGING,
  IAM_ROLE_SAVED_SEARCHES_PRODUCTION,
  IAM_ROLE_SAVED_SEARCHES_STAGING,
  IAM_ROLE_SCHOOL_PRODUCTION,
  IAM_ROLE_SCHOOL_STAGING,
  IAM_ROLE_SEARCH_FILTERS_CONFIG_DEVELOPMENT,
  IAM_ROLE_SEARCH_FILTERS_CONFIG_PRODUCTION,
  IAM_ROLE_SEARCH_FILTERS_CONFIG_STAGING,
  IAM_ROLE_SEARCH_UI_BUILDER_DEVELOPMENT,
  IAM_ROLE_SEARCH_UI_BUILDER_PRODUCTION,
  IAM_ROLE_SEARCH_UI_BUILDER_STAGING,
  IAM_ROLE_SEARCH_QUERIES_DEVELOPMENT,
  IAM_ROLE_SEARCH_QUERIES_PRODUCTION,
  IAM_ROLE_SEARCH_QUERIES_STAGING,
  IAM_ROLE_SEARCHER_PARENT_PRODUCTION,
  IAM_ROLE_SEARCHER_PARENT_STAGING,
  IAM_ROLE_SUGGESTIONS_DEVELOPMENT,
  IAM_ROLE_SUGGESTIONS_PRODUCTION,
  IAM_ROLE_SUGGESTIONS_STAGING,
  IAM_ROLE_SYNDICATION_AIRFLOW_WORKER_PRODUCTION,
  IAM_ROLE_SYNDICATION_AIRFLOW_WORKER_STAGING,
  IAM_ROLE_TOURS_MIGRATORS_SINGLETON_PRODUCTION,
  IAM_ROLE_TOURS_MIGRATORS_SINGLETON_STAGING,
  IAM_ROLE_TOURSHEET_PRODUCTION,
  IAM_ROLE_TOURSHEET_STAGING,
  IAM_ROLE_WORKSPACE_PRODUCTION,
  IAM_ROLE_WORKSPACE_STAGING,
  IAM_ROLE_ZOOKEEPER,
))

# Environment purpose role map

ENVIRONMENT_PURPOSE_IAM_ROLES = {
  INSTANCE_ENVIRONMENT_PRODUCTION: {
    INSTANCE_PURPOSE_ACTIVITY_FEED: IAM_ROLE_ACTIVITY_FEED_PRODUCTION,
    INSTANCE_PURPOSE_ACTIVITY_JOBS: IAM_ROLE_ACTIVITY_JOBS_PRODUCTION,
    INSTANCE_PURPOSE_ADDRESS_LOOKUP_SERVICE: IAM_ROLE_ADDRESS_LOOKUP_SERVICE_PRODUCTION,
    INSTANCE_PURPOSE_AIRFLOW_SCHEDULER: IAM_ROLE_AIRFLOW_SCHEDULER_PRODUCTION,
    INSTANCE_PURPOSE_AIRFLOW_WORKER: IAM_ROLE_AIRFLOW_WORKER_PRODUCTION,
    INSTANCE_PURPOSE_AIRFLOW_WORKER2: IAM_ROLE_AIRFLOW_WORKER_PRODUCTION,
    INSTANCE_PURPOSE_AIRFLOW_WORKER3: IAM_ROLE_AIRFLOW_WORKER_PRODUCTION,
    INSTANCE_PURPOSE_ASYNC_IMAGE_PROCESSOR: IAM_ROLE_IMAGE_PROCESSOR_PRODUCTION,
    INSTANCE_PURPOSE_BUILDINGS: IAM_ROLE_BUILDINGS_PRODUCTION,
    INSTANCE_PURPOSE_BUILDING_EDITORS: IAM_ROLE_BUILDING_EDITORS_PRODUCTION,
    INSTANCE_PURPOSE_COMMS_CONTACTS_JOBS: IAM_ROLE_COMMS_CONTACTS_JOBS_PRODUCTION,
    INSTANCE_PURPOSE_COMPASS_QIC: IAM_ROLE_COMPASS_QIC_PRODUCTION,
    INSTANCE_PURPOSE_CONTACT_EMAIL: IAM_ROLE_CONTACT_EMAIL_PRODUCTION,
    INSTANCE_PURPOSE_CONTACTS: IAM_ROLE_CONTACTS_PRODUCTION,
    INSTANCE_PURPOSE_CREATIVE_STUDIO: IAM_ROLE_CREATIVE_STUDIO_PRODUCTION,
    INSTANCE_PURPOSE_DATA_APIS: IAM_ROLE_DATA_APIS_PRODUCTION,
    INSTANCE_PURPOSE_DATA_DB: IAM_ROLE_DATA_MONGO_PRODUCTION,
    INSTANCE_PURPOSE_DATA_MONGO_BACKUP: IAM_ROLE_DATA_MONGO_BACKUP_PRODUCTION,
    INSTANCE_PURPOSE_DB: IAM_ROLE_MONGO_PRODUCTION,
    INSTANCE_PURPOSE_DEALS: IAM_ROLE_DEALS_PRODUCTION,
    INSTANCE_PURPOSE_DEALS_JOBS: IAM_ROLE_DEALS_JOBS_PRODUCTION,
    INSTANCE_PURPOSE_DEALS_MIGRATORS_SINGLETON: IAM_ROLE_DEALS_MIGRATORS_SINGLETON_PRODUCTION,
    INSTANCE_PURPOSE_DEPLOYER: IAM_ROLE_DEPLOYER,
    INSTANCE_PURPOSE_DOCUMENTS: IAM_ROLE_DOCUMENTS_PRODUCTION,
    INSTANCE_PURPOSE_EDITABLE_ACTIVITY: IAM_ROLE_EDITABLE_ACTIVITY_PRODUCTION,
    INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER2: IAM_ROLE_ELASTIC_SEARCH_INDEXER_PRODUCTION,
    INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER: IAM_ROLE_ELASTIC_SEARCH_INDEXER_PRODUCTION,
    INSTANCE_PURPOSE_ELASTIC_SEARCH_SEARCHER2: IAM_ROLE_ELASTIC_SEARCH_SEARCHER_PRODUCTION,
    INSTANCE_PURPOSE_ELASTIC_SEARCH_SEARCHER: IAM_ROLE_ELASTIC_SEARCH_SEARCHER_PRODUCTION,
    INSTANCE_PURPOSE_EMAIL_CAMPAIGN: IAM_ROLE_EMAIL_CAMPAIGN_PRODUCTION,
    INSTANCE_PURPOSE_EMR_JOBS: IAM_ROLE_EMR_JOBS_PRODUCTION,
    INSTANCE_PURPOSE_EVENTS_APIS: IAM_ROLE_EVENTS_LOGGER_PRODUCTION,
    INSTANCE_PURPOSE_FRONTEND: IAM_ROLE_FRONTEND_PRODUCTION,
    INSTANCE_PURPOSE_FRONTEND_CONFIG: IAM_ROLE_FRONTEND_CONFIG_PRODUCTION,
    INSTANCE_PURPOSE_FRONTEND_PROXY: IAM_ROLE_FRONTEND_PRODUCTION,
    INSTANCE_PURPOSE_FRONTEND_TIER1: IAM_ROLE_FRONTEND_PRODUCTION,
    INSTANCE_PURPOSE_FTP_TO_S3_MIRROR: IAM_ROLE_FTP_TO_S3_MIRROR_PRODUCTION,
    INSTANCE_PURPOSE_GENERIC_JOBS: IAM_ROLE_GENERIC_JOBS_PRODUCTION,
    INSTANCE_PURPOSE_GEOCODING: IAM_ROLE_GEOCODING_PRODUCTION,
    INSTANCE_PURPOSE_GEOCODING_SERVICE: IAM_ROLE_GEOCODING_SERVICE_PRODUCTION,
    INSTANCE_PURPOSE_GERRIT: IAM_ROLE_GERRIT,
    INSTANCE_PURPOSE_GI_APPS: IAM_ROLE_GI_APPS_PRODUCTION,
    INSTANCE_PURPOSE_GIS_SERVICE: IAM_ROLE_GIS_SERVICE_PRODUCTION,
    INSTANCE_PURPOSE_GIS_IMPORTER: IAM_ROLE_GIS_IMPORTER_PRODUCTION,
    INSTANCE_PURPOSE_GIS_SERVICE_TEST: IAM_ROLE_GIS_SERVICE_TEST_PRODUCTION,
    INSTANCE_PURPOSE_HELPER_TOOLS: IAM_ROLE_HELPER_TOOLS_PRODUCTION,
    INSTANCE_PURPOSE_IDENTITY: IAM_ROLE_IDENTITY_PRODUCTION,
    INSTANCE_PURPOSE_IMAGE_PROCESSOR: IAM_ROLE_IMAGE_PROCESSOR_PRODUCTION,
    INSTANCE_PURPOSE_IMAGE_RESPONSE_PROCESSOR: IAM_ROLE_IMAGE_RESPONSE_PROCESSOR_PRODUCTION,
    INSTANCE_PURPOSE_INDEXER2: IAM_ROLE_ELASTIC_SEARCH_INDEXER_PRODUCTION,
    INSTANCE_PURPOSE_INDEXER3: IAM_ROLE_ELASTIC_SEARCH_INDEXER_PRODUCTION,
    INSTANCE_PURPOSE_INDEXER4: IAM_ROLE_ELASTIC_SEARCH_INDEXER_PRODUCTION,
    INSTANCE_PURPOSE_INDEXER: IAM_ROLE_ELASTIC_SEARCH_INDEXER_PRODUCTION,
    INSTANCE_PURPOSE_INDEXER_STREAM_PRODUCER1: IAM_ROLE_INDEXER_STREAM_PRODUCER_PRODUCTION1,
    INSTANCE_PURPOSE_INDEXER_STREAM_PRODUCER2: IAM_ROLE_INDEXER_STREAM_PRODUCER_PRODUCTION2,
    INSTANCE_PURPOSE_INFORMATICA: IAM_ROLE_INFORMATICA_PRODUCTION,
    INSTANCE_PURPOSE_INGESTION_JOBS: IAM_ROLE_INGESTION_JOBS_PRODUCTION,
    INSTANCE_PURPOSE_INSIGHTS_APIS: IAM_ROLE_INSIGHTS_APIS_PRODUCTION,
    INSTANCE_PURPOSE_INSIGHTS_JOBS: IAM_ROLE_INSIGHTS_JOBS_PRODUCTION,
    INSTANCE_PURPOSE_TOKENS: IAM_ROLE_TOKENS_PRODUCTION,
    INSTANCE_PURPOSE_KUBERNETES_DEPLOYER: IAM_ROLE_KUBERNETES_DEPLOYER,
    INSTANCE_PURPOSE_LISTING_EDITORS: IAM_ROLE_LISTING_EDITORS_PRODUCTION,
    INSTANCE_PURPOSE_LISTINGS_NORMALIZATION: IAM_ROLE_LISTINGS_NORMALIZATION_PRODUCTION,
    INSTANCE_PURPOSE_LISTINGS_NORMALIZATION_REALTIME: IAM_ROLE_LISTINGS_NORMALIZATION_PRODUCTION,
    INSTANCE_PURPOSE_LISTING_SCHOOL: IAM_ROLE_DATA_APIS_PRODUCTION,
    INSTANCE_PURPOSE_LISTINGS_SERVICE: IAM_ROLE_LISTINGS_PRODUCTION,
    INSTANCE_PURPOSE_LOCALES: IAM_ROLE_LOCALES_PRODUCTION,
    INSTANCE_PURPOSE_MARKETING_CENTER: IAM_ROLE_MARKETING_CENTER_PRODUCTION,
    INSTANCE_PURPOSE_MESSIER: IAM_ROLE_MESSIER_PRODUCTION,
    INSTANCE_PURPOSE_MESSIER_INSTANT: IAM_ROLE_MESSIER_PRODUCTION,
    INSTANCE_PURPOSE_MONGO_BACKUP: IAM_ROLE_MONGO_BACKUP_PRODUCTION,
    INSTANCE_PURPOSE_NETWORK: IAM_ROLE_NETWORK_PRODUCTION,
    INSTANCE_PURPOSE_NOTIFICATION: IAM_ROLE_NOTIFICATION_PRODUCTION,
    INSTANCE_PURPOSE_NPM_ENTERPRISE: IAM_ROLE_NPM,
    INSTANCE_PURPOSE_OPEN_HOUSE: IAM_ROLE_OPEN_HOUSE_PRODUCTION,
    INSTANCE_PURPOSE_OPEN_HOUSE_JOBS: IAM_ROLE_OPEN_HOUSE_JOBS_PRODUCTION,
    INSTANCE_PURPOSE_PACKER: IAM_ROLE_PACKER,
    INSTANCE_PURPOSE_PDF_EXPORT: IAM_ROLE_PDF_EXPORT_PRODUCTION,
    INSTANCE_PURPOSE_PEOPLE: IAM_ROLE_PEOPLE_PRODUCTION,
    INSTANCE_PURPOSE_PEOPLE_JOBS: IAM_ROLE_PEOPLE_JOBS_PRODUCTION,
    INSTANCE_PURPOSE_PERCOLATE_PROCESSOR: IAM_ROLE_PERCOLATE_PROCESSOR_PRODUCTION,
    INSTANCE_PURPOSE_PERMISSIONS: IAM_ROLE_PERMISSIONS_PRODUCTION,
    INSTANCE_PURPOSE_PHYSICAL_SIGNS: IAM_ROLE_PHYSICAL_SIGNS_PRODUCTION,
    INSTANCE_PURPOSE_PLATFORM: IAM_ROLE_PLATFORM_PRODUCTION,
    INSTANCE_PURPOSE_PLATFORM_SEARCH: IAM_ROLE_PLATFORM_PRODUCTION,
    INSTANCE_PURPOSE_PROMOTE_JOBS: IAM_ROLE_PROMOTE_JOBS_PRODUCTION,
    INSTANCE_PURPOSE_PROPERTIES: IAM_ROLE_PROPERTIES_PRODUCTION,
    INSTANCE_PURPOSE_REDIRECT: IAM_ROLE_REDIRECT,
    INSTANCE_PURPOSE_RENORMALIZE_SERVICE: IAM_ROLE_RENORMALIZE_SERVICE_PRODUCTION,
    INSTANCE_PURPOSE_RESEARCH_ANALYTICS: IAM_ROLE_RESEARCH_ANALYTICAL_FRAMEWORK_PRODUCTION,
    INSTANCE_PURPOSE_RESEARCH_APIS: IAM_ROLE_RESEARCH_APIS_PRODUCTION,
    INSTANCE_PURPOSE_RESEARCH_JOBS: IAM_ROLE_RESEARCH_JOBS_PRODUCTION,
    INSTANCE_PURPOSE_SCHOOL: IAM_ROLE_SCHOOL_PRODUCTION,
    INSTANCE_PURPOSE_SEARCH_UI_BUILDER: IAM_ROLE_SEARCH_UI_BUILDER_PRODUCTION,
    INSTANCE_PURPOSE_SAVED_SEARCH: IAM_ROLE_SAVED_SEARCH_PRODUCTION,
    INSTANCE_PURPOSE_SAVED_SEARCHES: IAM_ROLE_SAVED_SEARCHES_PRODUCTION,
    INSTANCE_PURPOSE_SAVED_SEARCHES2: IAM_ROLE_SAVED_SEARCHES_PRODUCTION,
    INSTANCE_PURPOSE_SEARCH_FILTERS_CONFIG: IAM_ROLE_SEARCH_FILTERS_CONFIG_PRODUCTION,
    INSTANCE_PURPOSE_SEARCH_QUERIES: IAM_ROLE_SEARCH_QUERIES_PRODUCTION,
    INSTANCE_PURPOSE_SEARCHER2: IAM_ROLE_ELASTIC_SEARCH_SEARCHER_PRODUCTION,
    INSTANCE_PURPOSE_SEARCHER3: IAM_ROLE_ELASTIC_SEARCH_SEARCHER_PRODUCTION,
    INSTANCE_PURPOSE_SEARCHER4: IAM_ROLE_ELASTIC_SEARCH_SEARCHER_PRODUCTION,
    INSTANCE_PURPOSE_SEARCHER: IAM_ROLE_ELASTIC_SEARCH_SEARCHER_PRODUCTION,
    INSTANCE_PURPOSE_SEARCHER_PARENT: IAM_ROLE_SEARCHER_PARENT_PRODUCTION,
    INSTANCE_PURPOSE_SUGGESTIONS: IAM_ROLE_SUGGESTIONS_PRODUCTION,
    INSTANCE_PURPOSE_SYNDICATION_AIRFLOW_WORKER: IAM_ROLE_SYNDICATION_AIRFLOW_WORKER_PRODUCTION,
    INSTANCE_PURPOSE_LISTINGS_EXPORTER_JOBS: IAM_ROLE_LISTINGS_EXPORTER_JOBS_PRODUCTION,
    INSTANCE_PURPOSE_GIS_SERVICE_EXPORTER_JOBS: IAM_ROLE_GIS_SERVICE_EXPORTER_JOBS_PRODUCTION,
    INSTANCE_PURPOSE_TASKS: IAM_ROLE_TASKS_PRODUCTION,
    INSTANCE_PURPOSE_TRANSIT: IAM_ROLE_TRANSIT_PRODUCTION,
    INSTANCE_PURPOSE_TOURS_MIGRATORS_SINGLETON: IAM_ROLE_TOURS_MIGRATORS_SINGLETON_PRODUCTION,
    INSTANCE_PURPOSE_TOURSHEET: IAM_ROLE_TOURSHEET_PRODUCTION,
    INSTANCE_PURPOSE_WORKSPACE: IAM_ROLE_WORKSPACE_PRODUCTION,
    INSTANCE_PURPOSE_ZOOKEEPER: IAM_ROLE_ZOOKEEPER,
  },
  INSTANCE_ENVIRONMENT_STAGING: {
    INSTANCE_PURPOSE_ACTIVITY_FEED: IAM_ROLE_ACTIVITY_FEED_STAGING,
    INSTANCE_PURPOSE_ACTIVITY_JOBS: IAM_ROLE_ACTIVITY_JOBS_STAGING,
    INSTANCE_PURPOSE_ADDRESS_LOOKUP_SERVICE: IAM_ROLE_ADDRESS_LOOKUP_SERVICE_STAGING,
    INSTANCE_PURPOSE_AIRFLOW_SCHEDULER: IAM_ROLE_AIRFLOW_SCHEDULER_STAGING,
    INSTANCE_PURPOSE_AIRFLOW_WORKER: IAM_ROLE_AIRFLOW_WORKER_STAGING,
    INSTANCE_PURPOSE_AIRFLOW_WORKER2: IAM_ROLE_AIRFLOW_WORKER_STAGING,
    INSTANCE_PURPOSE_AIRFLOW_WORKER3: IAM_ROLE_AIRFLOW_WORKER_STAGING,
    INSTANCE_PURPOSE_ASYNC_IMAGE_PROCESSOR: IAM_ROLE_IMAGE_PROCESSOR_STAGING,
    INSTANCE_PURPOSE_BUILDINGS: IAM_ROLE_BUILDINGS_STAGING,
    INSTANCE_PURPOSE_BUILDING_EDITORS: IAM_ROLE_BUILDING_EDITORS_STAGING,
    INSTANCE_PURPOSE_COMPASS_QIC: IAM_ROLE_COMPASS_QIC_STAGING,
    INSTANCE_PURPOSE_COMMS_CONTACTS_JOBS: IAM_ROLE_COMMS_CONTACTS_JOBS_STAGING,
    INSTANCE_PURPOSE_CONTACT_EMAIL: IAM_ROLE_CONTACT_EMAIL_STAGING,
    INSTANCE_PURPOSE_CONTACTS: IAM_ROLE_CONTACTS_STAGING,
    INSTANCE_PURPOSE_CREATIVE_STUDIO: IAM_ROLE_CREATIVE_STUDIO_STAGING,
    INSTANCE_PURPOSE_DATA_APIS: IAM_ROLE_DATA_APIS_STAGING,
    INSTANCE_PURPOSE_DATA_DB: IAM_ROLE_DATA_MONGO_STAGING,
    INSTANCE_PURPOSE_DATA_INTEGRATION_TEST: IAM_ROLE_DATA_INTEGRATION_TEST_STAGING,
    INSTANCE_PURPOSE_DATA_MONGO_BACKUP: IAM_ROLE_DATA_MONGO_BACKUP_STAGING,
    INSTANCE_PURPOSE_DB: IAM_ROLE_MONGO_STAGING,
    INSTANCE_PURPOSE_DEALS: IAM_ROLE_DEALS_STAGING,
    INSTANCE_PURPOSE_DEALS_JOBS: IAM_ROLE_DEALS_JOBS_STAGING,
    INSTANCE_PURPOSE_DEALS_MIGRATORS_SINGLETON: IAM_ROLE_DEALS_MIGRATORS_SINGLETON_STAGING,
    INSTANCE_PURPOSE_DOCUMENTS: IAM_ROLE_DOCUMENTS_STAGING,
    INSTANCE_PURPOSE_EDITABLE_ACTIVITY: IAM_ROLE_EDITABLE_ACTIVITY_STAGING,
    INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER3: IAM_ROLE_ELASTIC_SEARCH_INDEXER_STAGING,
    INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER2: IAM_ROLE_ELASTIC_SEARCH_INDEXER_STAGING,
    INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER: IAM_ROLE_ELASTIC_SEARCH_INDEXER_STAGING,
    INSTANCE_PURPOSE_ELASTIC_SEARCH_SEARCHER2: IAM_ROLE_ELASTIC_SEARCH_SEARCHER_STAGING,
    INSTANCE_PURPOSE_ELASTIC_SEARCH_SEARCHER: IAM_ROLE_ELASTIC_SEARCH_SEARCHER_STAGING,
    INSTANCE_PURPOSE_EMAIL_CAMPAIGN: IAM_ROLE_EMAIL_CAMPAIGN_STAGING,
    INSTANCE_PURPOSE_EMR_JOBS: IAM_ROLE_EMR_JOBS_STAGING,
    INSTANCE_PURPOSE_EVENTS_APIS: IAM_ROLE_EVENTS_LOGGER_STAGING,
    INSTANCE_PURPOSE_FRONTEND: IAM_ROLE_FRONTEND_STAGING,
    INSTANCE_PURPOSE_FRONTEND_CONFIG: IAM_ROLE_FRONTEND_CONFIG_STAGING,
    INSTANCE_PURPOSE_FRONTEND_PROXY: IAM_ROLE_FRONTEND_STAGING,
    INSTANCE_PURPOSE_FRONTEND_TIER1: IAM_ROLE_FRONTEND_STAGING,
    INSTANCE_PURPOSE_FTP_TO_S3_MIRROR: IAM_ROLE_FTP_TO_S3_MIRROR_STAGING,
    INSTANCE_PURPOSE_GENERIC_JOBS: IAM_ROLE_GENERIC_JOBS_STAGING,
    INSTANCE_PURPOSE_GEOCODING: IAM_ROLE_GEOCODING_STAGING,
    INSTANCE_PURPOSE_GEOCODING_SERVICE: IAM_ROLE_GEOCODING_SERVICE_STAGING,
    INSTANCE_PURPOSE_GI_APPS: IAM_ROLE_GI_APPS_STAGING,
    INSTANCE_PURPOSE_GIS_SERVICE: IAM_ROLE_GIS_SERVICE_STAGING,
    INSTANCE_PURPOSE_GIS_IMPORTER: IAM_ROLE_GIS_IMPORTER_STAGING,
    INSTANCE_PURPOSE_GIS_SERVICE_TEST: IAM_ROLE_GIS_SERVICE_TEST_STAGING,
    INSTANCE_PURPOSE_HELPER_TOOLS: IAM_ROLE_HELPER_TOOLS_STAGING,
    INSTANCE_PURPOSE_IDENTITY: IAM_ROLE_IDENTITY_STAGING,
    INSTANCE_PURPOSE_IMAGE_PROCESSOR: IAM_ROLE_IMAGE_PROCESSOR_STAGING,
    INSTANCE_PURPOSE_IMAGE_RESPONSE_PROCESSOR: IAM_ROLE_IMAGE_RESPONSE_PROCESSOR_STAGING,
    INSTANCE_PURPOSE_INDEXER2: IAM_ROLE_ELASTIC_SEARCH_INDEXER_STAGING,
    INSTANCE_PURPOSE_INDEXER3: IAM_ROLE_ELASTIC_SEARCH_INDEXER_STAGING,
    INSTANCE_PURPOSE_INDEXER4: IAM_ROLE_ELASTIC_SEARCH_INDEXER_STAGING,
    INSTANCE_PURPOSE_INDEXER_STREAM_PRODUCER1: IAM_ROLE_INDEXER_STREAM_PRODUCER_STAGING1,
    INSTANCE_PURPOSE_INDEXER_STREAM_PRODUCER2: IAM_ROLE_INDEXER_STREAM_PRODUCER_STAGING2,
    INSTANCE_PURPOSE_INDEXER: IAM_ROLE_ELASTIC_SEARCH_INDEXER_STAGING,
    INSTANCE_PURPOSE_INFORMATICA: IAM_ROLE_INFORMATICA_STAGING,
    INSTANCE_PURPOSE_INGESTION_JOBS: IAM_ROLE_INGESTION_JOBS_STAGING,
    INSTANCE_PURPOSE_INSIGHTS_APIS: IAM_ROLE_INSIGHTS_APIS_STAGING,
    INSTANCE_PURPOSE_INSIGHTS_JOBS: IAM_ROLE_INSIGHTS_JOBS_STAGING,
    INSTANCE_PURPOSE_TOKENS: IAM_ROLE_TOKENS_STAGING,
    INSTANCE_PURPOSE_LISTING_EDITORS: IAM_ROLE_LISTING_EDITORS_STAGING,
    INSTANCE_PURPOSE_LISTINGS_NORMALIZATION: IAM_ROLE_LISTINGS_NORMALIZATION_STAGING,
    INSTANCE_PURPOSE_LISTINGS_NORMALIZATION_REALTIME: IAM_ROLE_LISTINGS_NORMALIZATION_STAGING,
    INSTANCE_PURPOSE_LISTING_SCHOOL: IAM_ROLE_DATA_APIS_STAGING,
    INSTANCE_PURPOSE_LISTINGS_SERVICE: IAM_ROLE_LISTINGS_STAGING,
    INSTANCE_PURPOSE_LOCALES: IAM_ROLE_LOCALES_STAGING,
    INSTANCE_PURPOSE_MARKETING_CENTER: IAM_ROLE_MARKETING_CENTER_STAGING,
    INSTANCE_PURPOSE_MESSIER: IAM_ROLE_MESSIER_STAGING,
    INSTANCE_PURPOSE_MESSIER_INSTANT: IAM_ROLE_MESSIER_STAGING,
    INSTANCE_PURPOSE_MONGO_BACKUP: IAM_ROLE_MONGO_BACKUP_STAGING,
    INSTANCE_PURPOSE_NETWORK: IAM_ROLE_NETWORK_STAGING,
    INSTANCE_PURPOSE_NOTIFICATION: IAM_ROLE_NOTIFICATION_STAGING,
    INSTANCE_PURPOSE_OPEN_HOUSE: IAM_ROLE_OPEN_HOUSE_STAGING,
    INSTANCE_PURPOSE_OPEN_HOUSE_JOBS: IAM_ROLE_OPEN_HOUSE_JOBS_STAGING,
    INSTANCE_PURPOSE_PACKER: IAM_ROLE_PACKER,
    INSTANCE_PURPOSE_PDF_EXPORT: IAM_ROLE_PDF_EXPORT_STAGING,
    INSTANCE_PURPOSE_PEOPLE: IAM_ROLE_PEOPLE_STAGING,
    INSTANCE_PURPOSE_PEOPLE_JOBS: IAM_ROLE_PEOPLE_JOBS_STAGING,
    INSTANCE_PURPOSE_PERCOLATE_PROCESSOR: IAM_ROLE_PERCOLATE_PROCESSOR_STAGING,
    INSTANCE_PURPOSE_PERMISSIONS: IAM_ROLE_PERMISSIONS_STAGING,
    INSTANCE_PURPOSE_PHYSICAL_SIGNS: IAM_ROLE_PHYSICAL_SIGNS_STAGING,
    INSTANCE_PURPOSE_PLATFORM: IAM_ROLE_PLATFORM_STAGING,
    INSTANCE_PURPOSE_PLATFORM_SEARCH: IAM_ROLE_PLATFORM_STAGING,
    INSTANCE_PURPOSE_PROMOTE_JOBS: IAM_ROLE_PROMOTE_JOBS_STAGING,
    INSTANCE_PURPOSE_PROPERTIES: IAM_ROLE_PROPERTIES_STAGING,
    INSTANCE_PURPOSE_RENORMALIZE_SERVICE: IAM_ROLE_RENORMALIZE_SERVICE_STAGING,
    INSTANCE_PURPOSE_RESEARCH_APIS: IAM_ROLE_RESEARCH_APIS_STAGING,
    INSTANCE_PURPOSE_RESEARCH_JOBS: IAM_ROLE_RESEARCH_JOBS_STAGING,
    INSTANCE_PURPOSE_SAVED_SEARCH: IAM_ROLE_SAVED_SEARCH_STAGING,
    INSTANCE_PURPOSE_SAVED_SEARCHES: IAM_ROLE_SAVED_SEARCHES_STAGING,
    INSTANCE_PURPOSE_SAVED_SEARCHES2: IAM_ROLE_SAVED_SEARCHES_STAGING,
    INSTANCE_PURPOSE_SCHOOL: IAM_ROLE_SCHOOL_STAGING,
    INSTANCE_PURPOSE_SEARCH_FILTERS_CONFIG: IAM_ROLE_SEARCH_FILTERS_CONFIG_STAGING,
    INSTANCE_PURPOSE_SEARCH_QUERIES: IAM_ROLE_SEARCH_QUERIES_STAGING,
    INSTANCE_PURPOSE_SEARCH_UI_BUILDER: IAM_ROLE_SEARCH_UI_BUILDER_STAGING,
    INSTANCE_PURPOSE_SEARCHER2: IAM_ROLE_ELASTIC_SEARCH_SEARCHER_STAGING,
    INSTANCE_PURPOSE_SEARCHER3: IAM_ROLE_ELASTIC_SEARCH_SEARCHER_STAGING,
    INSTANCE_PURPOSE_SEARCHER4: IAM_ROLE_ELASTIC_SEARCH_SEARCHER_STAGING,
    INSTANCE_PURPOSE_SEARCHER: IAM_ROLE_ELASTIC_SEARCH_SEARCHER_STAGING,
    INSTANCE_PURPOSE_SEARCHER_PARENT: IAM_ROLE_SEARCHER_PARENT_STAGING,
    INSTANCE_PURPOSE_SUGGESTIONS: IAM_ROLE_SUGGESTIONS_STAGING,
    INSTANCE_PURPOSE_SYNDICATION_AIRFLOW_WORKER: IAM_ROLE_SYNDICATION_AIRFLOW_WORKER_STAGING,
    INSTANCE_PURPOSE_TASKS: IAM_ROLE_TASKS_STAGING,
    INSTANCE_PURPOSE_TOURS_MIGRATORS_SINGLETON: IAM_ROLE_TOURS_MIGRATORS_SINGLETON_STAGING,
    INSTANCE_PURPOSE_TOURSHEET: IAM_ROLE_TOURSHEET_STAGING,
    INSTANCE_PURPOSE_TRANSIT: IAM_ROLE_TRANSIT_STAGING,
    INSTANCE_PURPOSE_LISTINGS_EXPORTER_JOBS: IAM_ROLE_LISTINGS_EXPORTER_JOBS_STAGING,
    INSTANCE_PURPOSE_GIS_SERVICE_EXPORTER_JOBS: IAM_ROLE_GIS_SERVICE_EXPORTER_JOBS_STAGING,
    INSTANCE_PURPOSE_WORKSPACE: IAM_ROLE_WORKSPACE_STAGING,
    INSTANCE_PURPOSE_ZOOKEEPER: IAM_ROLE_ZOOKEEPER,
  },
  INSTANCE_ENVIRONMENT_DEVELOPMENT: {
    INSTANCE_PURPOSE_BASTION: IAM_ROLE_BASTION,
    INSTANCE_PURPOSE_COMPASS_QIC: IAM_ROLE_COMPASS_QIC_DEVELOPMENT,
    INSTANCE_PURPOSE_CONTACT_EMAIL: IAM_ROLE_CONTACT_EMAIL_DEVELOPMENT,
    INSTANCE_PURPOSE_CONTACTS: IAM_ROLE_CONTACTS_DEVELOPMENT,
    INSTANCE_PURPOSE_CREATIVE_STUDIO: IAM_ROLE_CREATIVE_STUDIO_DEVELOPMENT,
    INSTANCE_PURPOSE_DEMO: IAM_ROLE_FRONTEND_DEVELOPMENT,
    INSTANCE_PURPOSE_DEMO_POOL: IAM_ROLE_DEMO_POOL,
    INSTANCE_PURPOSE_EDITABLE_ACTIVITY: IAM_ROLE_EDITABLE_ACTIVITY_DEVELOPMENT,
    INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER2: IAM_ROLE_ELASTIC_SEARCH_INDEXER_STAGING,
    INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER3: IAM_ROLE_ELASTIC_SEARCH_INDEXER_STAGING,
    INSTANCE_PURPOSE_ELASTIC_SEARCH_SEARCHER2: IAM_ROLE_ELASTIC_SEARCH_SEARCHER_STAGING,
    INSTANCE_PURPOSE_FIVETRAN_BASTION: IAM_ROLE_BASTION,
    INSTANCE_PURPOSE_FF_TUNNELS: IAM_ROLE_FF_TUNNELS_DEVELOPMENT,
    INSTANCE_PURPOSE_FRONTEND_CONFIG: IAM_ROLE_FRONTEND_CONFIG_DEVELOPMENT,
    INSTANCE_PURPOSE_GI_APPS: IAM_ROLE_GI_APPS_DEVELOPMENT,
    INSTANCE_PURPOSE_INDEXER_STREAM_PRODUCER1: IAM_ROLE_INDEXER_STREAM_PRODUCER_STAGING1,
    INSTANCE_PURPOSE_INDEXER_STREAM_PRODUCER2: IAM_ROLE_INDEXER_STREAM_PRODUCER_STAGING2,
    INSTANCE_PURPOSE_TOKENS: IAM_ROLE_TOKENS_DEVELOPMENT,
    INSTANCE_PURPOSE_MESSIER: IAM_ROLE_MESSIER_DEVELOPMENT,
    INSTANCE_PURPOSE_GIS_SERVICE: IAM_ROLE_GIS_SERVICE_DEVELOPMENT,
    INSTANCE_PURPOSE_NETWORK: IAM_ROLE_NETWORK_DEVELOPMENT,
    INSTANCE_PURPOSE_NPM_ENTERPRISE: IAM_ROLE_NPM,
    INSTANCE_PURPOSE_OPENGROK: IAM_ROLE_OPENGROK,
    INSTANCE_PURPOSE_OPEN_HOUSE: IAM_ROLE_OPEN_HOUSE_DEVELOPMENT,
    INSTANCE_PURPOSE_OPEN_HOUSE_JOBS: IAM_ROLE_OPEN_HOUSE_JOBS_DEVELOPMENT,
    INSTANCE_PURPOSE_PERMISSIONS: IAM_ROLE_PERMISSIONS_DEVELOPMENT,
    INSTANCE_PURPOSE_SAVED_SEARCH: IAM_ROLE_SAVED_SEARCH_DEVELOPMENT,
    INSTANCE_PURPOSE_SEARCH_FILTERS_CONFIG: IAM_ROLE_SEARCH_FILTERS_CONFIG_DEVELOPMENT,
    INSTANCE_PURPOSE_SEARCH_QUERIES: IAM_ROLE_SEARCH_QUERIES_DEVELOPMENT,
    INSTANCE_PURPOSE_SEARCH_UI_BUILDER: IAM_ROLE_SEARCH_UI_BUILDER_DEVELOPMENT,
    INSTANCE_PURPOSE_SUGGESTIONS: IAM_ROLE_SUGGESTIONS_DEVELOPMENT,
    INSTANCE_PURPOSE_TESTING: IAM_ROLE_CLOUD_TESTING,
    INSTANCE_PURPOSE_SEARCHER_PARENT: IAM_ROLE_SEARCHER_PARENT_STAGING,
  },
  INSTANCE_ENVIRONMENT_LOAD_TESTING: {
    INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER2_LOAD_TEST: IAM_ROLE_ELASTIC_SEARCH_INDEXER_STAGING,
    INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER_LOAD_TEST: IAM_ROLE_ELASTIC_SEARCH_INDEXER_STAGING,
    INSTANCE_PURPOSE_INDEXER3_LOAD_TEST: IAM_ROLE_ELASTIC_SEARCH_INDEXER_STAGING,
    INSTANCE_PURPOSE_INDEXER_LOAD_TEST: IAM_ROLE_ELASTIC_SEARCH_INDEXER_STAGING,
  },
}

# Other miscellaneous constants

MANAGED_SUBDOMAIN = 'managed.compass.com'

MANAGED_SUBDOMAIN_RECORDS = (
  {
    'Name': 'managed.compass.com.',
    'Type': 'NS',
    'TTL': 172800,
    'ResourceRecords': [
      'ns-1536.awsdns-00.co.uk.',
      'ns-0.awsdns-00.com.',
      'ns-1024.awsdns-00.org.',
      'ns-512.awsdns-00.net.'
    ]
  },
  {
    'Name': 'managed.compass.com.',
    'Type': 'SOA',
    'TTL': 900,
    'ResourceRecords': [
      'ns-1536.awsdns-00.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400'
    ]
  },
)

MANAGED_AWS_KEY_PAIRS = {
  INSTANCE_ENVIRONMENT_PRODUCTION: 'production',
  INSTANCE_ENVIRONMENT_STAGING: 'development',
  INSTANCE_ENVIRONMENT_DEVELOPMENT: 'development',
  INSTANCE_ENVIRONMENT_LOAD_TESTING: 'development'
}

MANAGED_ENV_ROLEDEFS = {
  # TODO(ltd): other static roledefs that we're still gonna need go here
  'development': ['localhost'],
  'gerrit': ['urbancompass@gerrit.urbancompass.com'],
  'opengrok': ['urbancompass@opengrok.compass.com'],
  'staging_mongo_secondary_1': [
    'urbancompass@staging-mongo-08ebaf932654fd97b.managed.compass.com'
  ],
  'production_mongo_secondary_1': [
    'urbancompass@production-mongo-0be2725737a01e1cb.managed.compass.com'
  ],
  'production_mongo_secondary_2': [
    'urbancompass@production-mongo-01c23ad11cd9399a4.managed.compass.com'
  ],
  'production_data_mongo_secondary_1': [
    'urbancompass@production-data-mongo-74839bec.managed.compass.com'
  ],
}

MANAGED_ENV_PREFIXES = {
  # TODO(ltd): other static metric prefixes that we're still gonna need go here
  'localhost': 'development',
  '127.0.0.1': 'development',
  'gerrit.urbancompass.com': 'gerrit',
}

# Our current default EC2 instance type
INSTANCE_TYPE_DEFAULT = 'm3.xlarge'


# Backwards-compatibility shims
#   As a transitionary step, we still need to do a little bit of static role shimming. For
#   instance, we currently put a bunch of machines all on one of three "jobs" subnets in
#   production, whereas the instance discovery framework expects to have unique subnets for each
#   distinct role.

SUBNET_COMPATIBILITY_MAP = {
  INSTANCE_ENVIRONMENT_PRODUCTION: {
    # Currently both primaries and secondaries inhabit a single "mongo" subnet
    INSTANCE_PURPOSE_DATA_DB: 'mongo',
    INSTANCE_PURPOSE_DB: 'mongo',
    # Currently there exist 3 generic "frontend" subnets -- one for each AZ
    INSTANCE_PURPOSE_FRONTEND_PROXY: 'frontend',
    INSTANCE_PURPOSE_FRONTEND_TIER1: 'frontend',
    INSTANCE_PURPOSE_NPM_ENTERPRISE: 'frontend',
    # Currently there exist 3 generic "jobs" subnets -- one for each AZ
    INSTANCE_PURPOSE_ACTIVITY_FEED: 'jobs',
    INSTANCE_PURPOSE_ACTIVITY_JOBS: 'jobs',
    INSTANCE_PURPOSE_ADDRESS_LOOKUP_SERVICE: 'jobs',
    INSTANCE_PURPOSE_AIRFLOW_SCHEDULER: 'jobs',
    INSTANCE_PURPOSE_AIRFLOW_WORKER: 'jobs',
    INSTANCE_PURPOSE_AIRFLOW_WORKER2: 'jobs',
    INSTANCE_PURPOSE_AIRFLOW_WORKER3: 'jobs',
    INSTANCE_PURPOSE_ASYNC_IMAGE_PROCESSOR: 'jobs',
    INSTANCE_PURPOSE_BUILDINGS: 'jobs',
    INSTANCE_PURPOSE_BUILDING_EDITORS: 'jobs',
    INSTANCE_PURPOSE_COMPASS_QIC: 'jobs',
    INSTANCE_PURPOSE_COMMS_CONTACTS_JOBS: 'jobs',
    INSTANCE_PURPOSE_CONTACT_EMAIL: 'jobs',
    INSTANCE_PURPOSE_CONTACTS: 'jobs',
    INSTANCE_PURPOSE_CREATIVE_STUDIO: 'jobs',
    INSTANCE_PURPOSE_DATA_APIS: 'jobs',
    INSTANCE_PURPOSE_DATA_MONGO_BACKUP: 'jobs',
    INSTANCE_PURPOSE_DEALS: 'jobs',
    INSTANCE_PURPOSE_DEALS_JOBS: 'jobs',
    INSTANCE_PURPOSE_DEALS_MIGRATORS_SINGLETON: 'jobs',
    INSTANCE_PURPOSE_DEVOPS: 'jobs',
    INSTANCE_PURPOSE_DOCUMENTS: 'jobs',
    INSTANCE_PURPOSE_EDITABLE_ACTIVITY: 'jobs',
    INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER2: 'jobs',
    INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER: 'jobs',
    INSTANCE_PURPOSE_ELASTIC_SEARCH_SEARCHER2: 'jobs',
    INSTANCE_PURPOSE_ELASTIC_SEARCH_SEARCHER: 'jobs',
    INSTANCE_PURPOSE_EMAIL_CAMPAIGN: 'jobs',
    INSTANCE_PURPOSE_EMR_JOBS: 'jobs',
    INSTANCE_PURPOSE_EVENTS_APIS: 'jobs',
    INSTANCE_PURPOSE_FRONTEND_CONFIG: 'jobs',
    INSTANCE_PURPOSE_FTP_TO_S3_MIRROR: 'jobs',
    INSTANCE_PURPOSE_GEOCODING: 'jobs',
    INSTANCE_PURPOSE_GEOCODING_SERVICE: 'jobs',
    INSTANCE_PURPOSE_GI_APPS: 'jobs',
    INSTANCE_PURPOSE_GIS_SERVICE: 'jobs',
    INSTANCE_PURPOSE_GIS_IMPORTER: 'jobs',
    INSTANCE_PURPOSE_GIS_SERVICE_TEST: 'jobs',
    INSTANCE_PURPOSE_HELPER_TOOLS: 'jobs',
    INSTANCE_PURPOSE_IDENTITY: 'jobs',
    INSTANCE_PURPOSE_IMAGE_PROCESSOR: 'jobs',
    INSTANCE_PURPOSE_IMAGE_RESPONSE_PROCESSOR: 'jobs',
    INSTANCE_PURPOSE_INDEXER2: 'jobs',
    INSTANCE_PURPOSE_INDEXER3: 'jobs',
    INSTANCE_PURPOSE_INDEXER4: 'jobs',
    INSTANCE_PURPOSE_INDEXER: 'jobs',
    INSTANCE_PURPOSE_INDEXER_STREAM_PRODUCER1: 'jobs',
    INSTANCE_PURPOSE_INDEXER_STREAM_PRODUCER2: 'jobs',
    INSTANCE_PURPOSE_INFORMATICA: 'jobs',
    INSTANCE_PURPOSE_INGESTION_JOBS: 'jobs',
    INSTANCE_PURPOSE_INSIGHTS_APIS: 'jobs',
    INSTANCE_PURPOSE_INSIGHTS_JOBS: 'jobs',
    INSTANCE_PURPOSE_LISTING_DEBUG: 'jobs',
    INSTANCE_PURPOSE_LISTING_EDITORS: 'jobs',
    INSTANCE_PURPOSE_LISTINGS_NORMALIZATION: 'jobs',
    INSTANCE_PURPOSE_LISTINGS_NORMALIZATION_REALTIME: 'jobs',
    INSTANCE_PURPOSE_LISTING_SCHOOL: 'jobs',
    INSTANCE_PURPOSE_LISTINGS_SERVICE: 'jobs',
    INSTANCE_PURPOSE_LOCALES: 'jobs',
    INSTANCE_PURPOSE_MARKETING_CENTER: 'jobs',
    INSTANCE_PURPOSE_MESSIER: 'jobs',
    INSTANCE_PURPOSE_MESSIER_INSTANT: 'jobs',
    INSTANCE_PURPOSE_MONGO_BACKUP: 'jobs',
    INSTANCE_PURPOSE_NETWORK: 'jobs',
    INSTANCE_PURPOSE_NOTIFICATION: 'jobs',
    INSTANCE_PURPOSE_OPEN_HOUSE: 'jobs',
    INSTANCE_PURPOSE_OPEN_HOUSE_JOBS: 'jobs',
    INSTANCE_PURPOSE_PACKER: 'jobs',
    INSTANCE_PURPOSE_PDF_EXPORT: 'jobs',
    INSTANCE_PURPOSE_PEOPLE: 'jobs',
    INSTANCE_PURPOSE_PEOPLE_JOBS: 'jobs',
    INSTANCE_PURPOSE_PERCOLATE_PROCESSOR: 'jobs',
    INSTANCE_PURPOSE_PERMISSIONS: 'jobs',
    INSTANCE_PURPOSE_PHYSICAL_SIGNS: 'jobs',
    INSTANCE_PURPOSE_PLATFORM: 'jobs',
    INSTANCE_PURPOSE_PLATFORM_SEARCH: 'jobs',
    INSTANCE_PURPOSE_PROMOTE_JOBS: 'jobs',
    INSTANCE_PURPOSE_PROPERTIES: 'jobs',
    INSTANCE_PURPOSE_RENORMALIZE_SERVICE: 'jobs',
    INSTANCE_PURPOSE_RESEARCH_ANALYTICS: 'jobs',
    INSTANCE_PURPOSE_RESEARCH_APIS: 'jobs',
    INSTANCE_PURPOSE_RESEARCH_JOBS: 'jobs',
    INSTANCE_PURPOSE_SAVED_SEARCH: 'jobs',
    INSTANCE_PURPOSE_SAVED_SEARCHES: 'jobs',
    INSTANCE_PURPOSE_SAVED_SEARCHES2: 'jobs',
    INSTANCE_PURPOSE_SCHOOL: 'jobs',
    INSTANCE_PURPOSE_SEARCH_FILTERS_CONFIG: 'jobs',
    INSTANCE_PURPOSE_SEARCH_QUERIES: 'jobs',
    INSTANCE_PURPOSE_SEARCH_UI_BUILDER: 'jobs',
    INSTANCE_PURPOSE_SEARCHER2: 'jobs',
    INSTANCE_PURPOSE_SEARCHER3: 'jobs',
    INSTANCE_PURPOSE_SEARCHER4: 'jobs',
    INSTANCE_PURPOSE_SEARCHER: 'jobs',
    INSTANCE_PURPOSE_SEARCHER_PARENT: 'jobs',
    INSTANCE_PURPOSE_SUGGESTIONS: 'jobs',
    INSTANCE_PURPOSE_SYNDICATION_AIRFLOW_WORKER: 'jobs',
    INSTANCE_PURPOSE_LISTINGS_EXPORTER_JOBS: 'jobs',
    INSTANCE_PURPOSE_GIS_SERVICE_EXPORTER_JOBS: 'jobs',
    INSTANCE_PURPOSE_TASKS: 'jobs',
    INSTANCE_PURPOSE_TEST: 'jobs',
    INSTANCE_PURPOSE_TOKENS: 'jobs',
    INSTANCE_PURPOSE_TOURS_MIGRATORS_SINGLETON: 'jobs',
    INSTANCE_PURPOSE_TOURSHEET: 'jobs',
    INSTANCE_PURPOSE_TRANSIT: 'jobs',
    INSTANCE_PURPOSE_VPN: 'redirect',
    INSTANCE_PURPOSE_WORKSPACE: 'jobs',
    INSTANCE_PURPOSE_ZOOKEEPER: 'jobs',
    # Currently there exists 1 generic "deploy" subnet
    INSTANCE_PURPOSE_KUBERNETES_DEPLOYER: 'deploy',
  },

  INSTANCE_ENVIRONMENT_STAGING: {
    # Currently our staging subnets only exist for us-east-1a, us-east-1b, and us-east-1c,
    # with no distinction between the types of instances in each subnet.
    INSTANCE_PURPOSE_ACTIVITY_FEED: 'all',
    INSTANCE_PURPOSE_ACTIVITY_JOBS: 'all',
    INSTANCE_PURPOSE_ADDRESS_LOOKUP_SERVICE: 'all',
    INSTANCE_PURPOSE_AIRFLOW_SCHEDULER: 'all',
    INSTANCE_PURPOSE_AIRFLOW_WORKER: 'all',
    INSTANCE_PURPOSE_AIRFLOW_WORKER2: 'all',
    INSTANCE_PURPOSE_AIRFLOW_WORKER3: 'all',
    INSTANCE_PURPOSE_ASYNC_IMAGE_PROCESSOR: 'all',
    INSTANCE_PURPOSE_BUILDINGS: 'all',
    INSTANCE_PURPOSE_BUILDING_EDITORS: 'all',
    INSTANCE_PURPOSE_COMPASS_QIC: 'all',
    INSTANCE_PURPOSE_COMMS_CONTACTS_JOBS: 'all',
    INSTANCE_PURPOSE_CONTACT_EMAIL: 'all',
    INSTANCE_PURPOSE_CONTACTS: 'all',
    INSTANCE_PURPOSE_CREATIVE_STUDIO: 'all',
    INSTANCE_PURPOSE_DATA_APIS: 'all',
    INSTANCE_PURPOSE_DATA_DB: 'all',
    INSTANCE_PURPOSE_DATA_INTEGRATION_TEST: 'all',
    INSTANCE_PURPOSE_DATA_MONGO_BACKUP: 'all',
    INSTANCE_PURPOSE_DB: 'all',
    INSTANCE_PURPOSE_DEALS: 'all',
    INSTANCE_PURPOSE_DEALS_JOBS: 'all',
    INSTANCE_PURPOSE_DEALS_MIGRATORS_SINGLETON: 'all',
    INSTANCE_PURPOSE_DEVOPS: 'all',
    INSTANCE_PURPOSE_DOCUMENTS: 'all',
    INSTANCE_PURPOSE_EDITABLE_ACTIVITY: 'all',
    INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER3: 'all',
    INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER2: 'all',
    INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER: 'all',
    INSTANCE_PURPOSE_ELASTIC_SEARCH_SEARCHER2: 'all',
    INSTANCE_PURPOSE_ELASTIC_SEARCH_SEARCHER: 'all',
    INSTANCE_PURPOSE_EMAIL_CAMPAIGN: 'all',
    INSTANCE_PURPOSE_EMR_JOBS: 'all',
    INSTANCE_PURPOSE_EVENTS_APIS: 'all',
    INSTANCE_PURPOSE_FRONTEND: 'all',
    INSTANCE_PURPOSE_FRONTEND_CONFIG: 'all',
    INSTANCE_PURPOSE_FRONTEND_PROXY: 'all',
    INSTANCE_PURPOSE_FRONTEND_TIER1: 'all',
    INSTANCE_PURPOSE_FTP_TO_S3_MIRROR: 'all',
    INSTANCE_PURPOSE_GENERIC_JOBS: 'all',
    INSTANCE_PURPOSE_GEOCODING: 'all',
    INSTANCE_PURPOSE_GEOCODING_SERVICE: 'all',
    INSTANCE_PURPOSE_GI_APPS: 'all',
    INSTANCE_PURPOSE_GIS_SERVICE: 'all',
    INSTANCE_PURPOSE_GIS_IMPORTER: 'all',
    INSTANCE_PURPOSE_GIS_SERVICE_TEST: 'all',
    INSTANCE_PURPOSE_HELPER_TOOLS: 'all',
    INSTANCE_PURPOSE_IDENTITY: 'all',
    INSTANCE_PURPOSE_IMAGE_PROCESSOR: 'all',
    INSTANCE_PURPOSE_IMAGE_RESPONSE_PROCESSOR: 'all',
    INSTANCE_PURPOSE_INDEXER2: 'all',
    INSTANCE_PURPOSE_INDEXER3: 'all',
    INSTANCE_PURPOSE_INDEXER4: 'all',
    INSTANCE_PURPOSE_INDEXER: 'all',
    INSTANCE_PURPOSE_INDEXER_STREAM_PRODUCER1: 'all',
    INSTANCE_PURPOSE_INDEXER_STREAM_PRODUCER2: 'all',
    INSTANCE_PURPOSE_INFORMATICA: 'all',
    INSTANCE_PURPOSE_INGESTION_JOBS: 'all',
    INSTANCE_PURPOSE_INSIGHTS_APIS: 'all',
    INSTANCE_PURPOSE_INSIGHTS_JOBS: 'all',
    INSTANCE_PURPOSE_LISTING_DEBUG: 'all',
    INSTANCE_PURPOSE_LISTING_EDITORS: 'all',
    INSTANCE_PURPOSE_LISTINGS_EXPORTER_JOBS: 'all',
    INSTANCE_PURPOSE_GIS_SERVICE_EXPORTER_JOBS: 'all',
    INSTANCE_PURPOSE_LISTINGS_NORMALIZATION: 'all',
    INSTANCE_PURPOSE_LISTINGS_NORMALIZATION_REALTIME: 'all',
    INSTANCE_PURPOSE_LISTING_SCHOOL: 'all',
    INSTANCE_PURPOSE_LISTINGS_SERVICE: 'all',
    INSTANCE_PURPOSE_LOCALES: 'all',
    INSTANCE_PURPOSE_MARKETING_CENTER: 'all',
    INSTANCE_PURPOSE_MESSIER: 'all',
    INSTANCE_PURPOSE_MESSIER_INSTANT: 'all',
    INSTANCE_PURPOSE_MONGO_BACKUP: 'all',
    INSTANCE_PURPOSE_NETWORK: 'all',
    INSTANCE_PURPOSE_NOTIFICATION: 'all',
    INSTANCE_PURPOSE_OPEN_HOUSE: 'all',
    INSTANCE_PURPOSE_OPEN_HOUSE_JOBS: 'all',
    INSTANCE_PURPOSE_PACKER: 'all',
    INSTANCE_PURPOSE_PDF_EXPORT: 'all',
    INSTANCE_PURPOSE_PEOPLE: 'all',
    INSTANCE_PURPOSE_PEOPLE_JOBS: 'all',
    INSTANCE_PURPOSE_PERCOLATE_PROCESSOR: 'all',
    INSTANCE_PURPOSE_PERMISSIONS: 'all',
    INSTANCE_PURPOSE_PHYSICAL_SIGNS: 'all',
    INSTANCE_PURPOSE_PLATFORM: 'all',
    INSTANCE_PURPOSE_PLATFORM_SEARCH: 'all',
    INSTANCE_PURPOSE_PROMOTE_JOBS: 'all',
    INSTANCE_PURPOSE_PROPERTIES: 'all',
    INSTANCE_PURPOSE_RENORMALIZE_SERVICE: 'all',
    INSTANCE_PURPOSE_RESEARCH_ANALYTICS: 'all',
    INSTANCE_PURPOSE_RESEARCH_APIS: 'all',
    INSTANCE_PURPOSE_RESEARCH_JOBS: 'all',
    INSTANCE_PURPOSE_SAVED_SEARCH: 'all',
    INSTANCE_PURPOSE_SAVED_SEARCHES: 'all',
    INSTANCE_PURPOSE_SAVED_SEARCHES2: 'all',
    INSTANCE_PURPOSE_SCHOOL: 'all',
    INSTANCE_PURPOSE_SEARCH_FILTERS_CONFIG: 'all',
    INSTANCE_PURPOSE_SEARCH_UI_BUILDER: 'all',
    INSTANCE_PURPOSE_SEARCH_QUERIES: 'all',
    INSTANCE_PURPOSE_SEARCHER2: 'all',
    INSTANCE_PURPOSE_SEARCHER3: 'all',
    INSTANCE_PURPOSE_SEARCHER4: 'all',
    INSTANCE_PURPOSE_SEARCHER: 'all',
    INSTANCE_PURPOSE_SEARCHER_PARENT: 'all',
    INSTANCE_PURPOSE_SUGGESTIONS: 'all',
    INSTANCE_PURPOSE_SYNDICATION_AIRFLOW_WORKER: 'all',
    INSTANCE_PURPOSE_TASKS: 'all',
    INSTANCE_PURPOSE_TEST: 'all',
    INSTANCE_PURPOSE_TOKENS: 'all',
    INSTANCE_PURPOSE_TOURS_MIGRATORS_SINGLETON: 'all',
    INSTANCE_PURPOSE_TOURSHEET: 'all',
    INSTANCE_PURPOSE_TRANSIT: 'all',
    INSTANCE_PURPOSE_WORKSPACE: 'all',
  },

  INSTANCE_ENVIRONMENT_DEVELOPMENT: {
    INSTANCE_PURPOSE_ACTIVITY_JOBS: 'testing',
    INSTANCE_PURPOSE_ADDRESS_LOOKUP_SERVICE: 'testing',
    INSTANCE_PURPOSE_AIRFLOW_SCHEDULER: 'testing',
    INSTANCE_PURPOSE_AIRFLOW_WORKER: 'testing',
    INSTANCE_PURPOSE_AIRFLOW_WORKER2: 'testing',
    INSTANCE_PURPOSE_AIRFLOW_WORKER3: 'testing',
    INSTANCE_PURPOSE_BASTION: 'testing',
    INSTANCE_PURPOSE_BUILDINGS: 'testing',
    INSTANCE_PURPOSE_BUILDING_EDITORS: 'testing',
    INSTANCE_PURPOSE_COMPASS_QIC: 'testing',
    INSTANCE_PURPOSE_COMMS_CONTACTS_JOBS: 'testing',
    INSTANCE_PURPOSE_CONTACT_EMAIL: 'testing',
    INSTANCE_PURPOSE_CONTACTS: 'testing',
    INSTANCE_PURPOSE_CREATIVE_STUDIO: 'testing',
    INSTANCE_PURPOSE_DATA_MONGO_BACKUP: 'testing',
    INSTANCE_PURPOSE_DB: 'testing',
    INSTANCE_PURPOSE_DEALS: 'testing',
    INSTANCE_PURPOSE_DEALS_JOBS: 'testing',
    INSTANCE_PURPOSE_DEALS_MIGRATORS_SINGLETON: 'testing',
    INSTANCE_PURPOSE_DEMO: 'testing',
    INSTANCE_PURPOSE_DEMO_POOL: 'testing',
    INSTANCE_PURPOSE_DOCUMENTS: 'testing',
    INSTANCE_PURPOSE_EDITABLE_ACTIVITY: 'testing',
    INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER3: 'testing',
    INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER2: 'testing',
    INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER2_LOAD_TEST: 'testing',
    INSTANCE_PURPOSE_ELASTIC_SEARCH_INDEXER_LOAD_TEST: 'testing',
    INSTANCE_PURPOSE_ELASTIC_SEARCH_SEARCHER2: 'testing',
    INSTANCE_PURPOSE_EMAIL_CAMPAIGN: 'testing',
    INSTANCE_PURPOSE_EVENTS_APIS: 'testing',
    INSTANCE_PURPOSE_FIVETRAN_BASTION: 'testing',
    INSTANCE_PURPOSE_FF_TUNNELS: 'testing',
    INSTANCE_PURPOSE_FRONTEND_CONFIG: 'testing',
    INSTANCE_PURPOSE_FTP_TO_S3_MIRROR: 'testing',
    INSTANCE_PURPOSE_GEOCODING_SERVICE: 'testing',
    INSTANCE_PURPOSE_GERRIT: 'tools',
    INSTANCE_PURPOSE_GI_APPS: 'testing',
    INSTANCE_PURPOSE_GIS_SERVICE: 'testing',
    INSTANCE_PURPOSE_GIS_SERVICE_TEST: 'testing',
    INSTANCE_PURPOSE_HELPER_TOOLS: 'testing',
    INSTANCE_PURPOSE_IDENTITY: 'testing',
    INSTANCE_PURPOSE_INDEXER3_LOAD_TEST: 'testing',
    INSTANCE_PURPOSE_INDEXER_LOAD_TEST: 'testing',
    INSTANCE_PURPOSE_INDEXER_STREAM_PRODUCER1: 'testing',
    INSTANCE_PURPOSE_INDEXER_STREAM_PRODUCER2: 'testing',
    INSTANCE_PURPOSE_INFORMATICA: 'testing',
    INSTANCE_PURPOSE_INSIGHTS_APIS: 'testing',
    INSTANCE_PURPOSE_INSIGHTS_JOBS: 'testing',
    INSTANCE_PURPOSE_KAFKA_COMPONENT: 'kafka',
    INSTANCE_PURPOSE_LISTING_EDITORS: 'testing',
    INSTANCE_PURPOSE_MARKETING_CENTER: 'testing',
    INSTANCE_PURPOSE_MESSIER: 'testing',
    INSTANCE_PURPOSE_MONGO_BACKUP: 'testing',
    INSTANCE_PURPOSE_NETWORK: 'testing',
    INSTANCE_PURPOSE_NOTIFICATION: 'testing',
    INSTANCE_PURPOSE_NPM_ENTERPRISE: 'tools',
    INSTANCE_PURPOSE_OPENGROK: 'tools',
    INSTANCE_PURPOSE_OPEN_HOUSE: 'testing',
    INSTANCE_PURPOSE_OPEN_HOUSE_JOBS: 'testing',
    INSTANCE_PURPOSE_PDF_EXPORT: 'testing',
    INSTANCE_PURPOSE_PEOPLE: 'testing',
    INSTANCE_PURPOSE_PEOPLE_JOBS: 'testing',
    INSTANCE_PURPOSE_PERMISSIONS: 'testing',
    INSTANCE_PURPOSE_PHYSICAL_SIGNS: 'testing',
    INSTANCE_PURPOSE_PLATFORM: 'testing',
    INSTANCE_PURPOSE_PLATFORM_SEARCH: 'testing',
    INSTANCE_PURPOSE_PROMOTE_JOBS: 'testing',
    INSTANCE_PURPOSE_PROPERTIES: 'testing',
    INSTANCE_PURPOSE_RENORMALIZE_SERVICE: 'testing',
    INSTANCE_PURPOSE_RESEARCH_ANALYTICS: 'testing',
    INSTANCE_PURPOSE_RESEARCH_APIS: 'testing',
    INSTANCE_PURPOSE_RESEARCH_JOBS: 'testing',
    INSTANCE_PURPOSE_SAVED_SEARCH: 'testing',
    INSTANCE_PURPOSE_SEARCH_FILTERS_CONFIG: 'testing',
    INSTANCE_PURPOSE_SEARCH_QUERIES: 'testing',
    INSTANCE_PURPOSE_SEARCH_UI_BUILDER: 'testing',
    INSTANCE_PURPOSE_SEARCHER_PARENT: 'testing',
    INSTANCE_PURPOSE_SUGGESTIONS: 'testing',
    INSTANCE_PURPOSE_TOKENS: 'testing',
    INSTANCE_PURPOSE_TOURS_MIGRATORS_SINGLETON: 'testing',
    INSTANCE_PURPOSE_TRANSIT: 'testing',
    INSTANCE_PURPOSE_WORKSPACE: 'testing',
  }
}
